// Generated by codegen/typescript/gen-orval-config.ts. DO NOT EDIT BY HAND.
// Regenerate with: make generate-typescript SCHEMA_DIR=<siennaschemas checkout>
import { defineConfig } from "orval";
import { isAbsolute, join, resolve } from "node:path";

// Resolved at orval runtime, never baked in. A committed config that embedded
// an absolute path would regenerate differently on every machine -- CI passes
// $GITHUB_WORKSPACE and checks SiennaSchemas out INSIDE the workspace, while a
// local checkout is usually a sibling of the repo, so even a relative path
// differs (../SiennaSchemas vs ../../SiennaSchemas). Resolving here keeps the
// artifact identical everywhere, which is what the CI drift check requires.
// Relative values resolve against the repo root, matching the Makefile, which
// runs orval from there.
const schemaDirEnv = process.env.SCHEMA_DIR ?? "../SiennaSchemas";
const SCHEMA_DIR = isAbsolute(schemaDirEnv)
  ? schemaDirEnv
  : resolve(process.cwd(), schemaDirEnv);

// Every *.json file under Core/, Operations/, Dynamics/, Investments/, and
// TimeSeries/ in the schema checkout -- see the generator's header comment
// for why this is a superset rather than each domain's exact $ref set.
const EXTERNAL_REFS_ALLOW = [
  "Core/Associations/SupplementalAttributeAssociation.json",
  "Core/SupplementalAttributes/DataSource.json",
  "Core/SupplementalAttributes/EmissionsData.json",
  "Core/SupplementalAttributes/GeographicInfo.json",
  "Core/SystemDocument.json",
  "Core/Topology/ACBus.json",
  "Core/Topology/Arc.json",
  "Core/Topology/Area.json",
  "Core/Topology/DCBus.json",
  "Core/Topology/LoadZone.json",
  "Core/common.json",
  "Core/units.json",
  "Dynamics/DynamicGeneratorComponent/RoundRotorMachine.json",
  "Dynamics/DynamicGeneratorComponent/SEXS.json",
  "Dynamics/DynamicGeneratorComponent/SteamTurbineGov1.json",
  "Dynamics/DynamicInverterComponent/ActiveRenewableControllerAB.json",
  "Dynamics/DynamicInverterComponent/RECurrentControlB.json",
  "Dynamics/DynamicInverterComponent/ReactiveRenewableControllerAB.json",
  "Dynamics/DynamicInverterComponent/RenewableEnergyConverterTypeA.json",
  "Investments/Associations/RequirementAssociation.json",
  "Investments/Financials/PortfolioFinancialData.json",
  "Investments/Financials/TechnologyFinancialData.json",
  "Investments/PortfolioDocument.json",
  "Investments/Requirements/CapacityReserveMargin.json",
  "Investments/Requirements/CarbonCaps.json",
  "Investments/Requirements/CarbonTax.json",
  "Investments/Requirements/EnergyShareRequirements.json",
  "Investments/Requirements/HourlyMatching.json",
  "Investments/Requirements/MaximumCapacityRequirements.json",
  "Investments/Requirements/MinimumCapacityRequirements.json",
  "Investments/SupplementalAttributes/ExistingDevices.json",
  "Investments/SupplementalAttributes/RetirementPotential.json",
  "Investments/SupplementalAttributes/RetrofitPotential.json",
  "Investments/SupplementalAttributes/TopologyMapping.json",
  "Investments/Technologies/AggregateTransportTechnology.json",
  "Investments/Technologies/ColocatedSupplyStorageTechnology.json",
  "Investments/Technologies/DemandRequirement.json",
  "Investments/Technologies/DemandSideTechnology.json",
  "Investments/Technologies/NodalACTransportTechnology.json",
  "Investments/Technologies/NodalHVDCTransportTechnology.json",
  "Investments/Technologies/StorageTechnology.json",
  "Investments/Technologies/SupplyTechnology.json",
  "Operations/Associations/CombinedCycleAssociation.json",
  "Operations/Associations/PlantAssociation.json",
  "Operations/Associations/ServiceAssociation.json",
  "Operations/Associations/TradingHubAssociation.json",
  "Operations/Branch/AreaInterchange.json",
  "Operations/Branch/DiscreteControlledACBranch.json",
  "Operations/Branch/GenericArcImpedance.json",
  "Operations/Branch/Line.json",
  "Operations/Branch/MonitoredLine.json",
  "Operations/Branch/TModelHVDCLine.json",
  "Operations/Branch/ThreeWindingTransformer.json",
  "Operations/Branch/TransformerCircuit.json",
  "Operations/Branch/TwoTerminalGenericHVDCLine.json",
  "Operations/Branch/TwoTerminalLCCLine.json",
  "Operations/Branch/TwoTerminalVSCLine.json",
  "Operations/Branch/TwoWindingTransformer.json",
  "Operations/Market/BilateralTransaction.json",
  "Operations/Market/PointToPointBid.json",
  "Operations/Market/TradingHub.json",
  "Operations/Market/VirtualParticipant.json",
  "Operations/Service/AGC.json",
  "Operations/Service/GroupReserve.json",
  "Operations/Service/OfflineReserve.json",
  "Operations/Service/OnlineReserve.json",
  "Operations/Service/TransmissionInterface.json",
  "Operations/StaticInjection/EnergyReservoirStorage.json",
  "Operations/StaticInjection/ExponentialLoad.json",
  "Operations/StaticInjection/FACTSControlDevice.json",
  "Operations/StaticInjection/FixedAdmittance.json",
  "Operations/StaticInjection/HybridSystem.json",
  "Operations/StaticInjection/HydroDispatch.json",
  "Operations/StaticInjection/HydroPumpTurbine.json",
  "Operations/StaticInjection/HydroReservoir.json",
  "Operations/StaticInjection/HydroTurbine.json",
  "Operations/StaticInjection/InterconnectingConverter.json",
  "Operations/StaticInjection/InterruptiblePowerLoad.json",
  "Operations/StaticInjection/InterruptibleStandardLoad.json",
  "Operations/StaticInjection/MotorLoad.json",
  "Operations/StaticInjection/PowerLoad.json",
  "Operations/StaticInjection/RenewableDispatch.json",
  "Operations/StaticInjection/RenewableNonDispatch.json",
  "Operations/StaticInjection/ShiftablePowerLoad.json",
  "Operations/StaticInjection/Source.json",
  "Operations/StaticInjection/StandardLoad.json",
  "Operations/StaticInjection/SwitchedAdmittance.json",
  "Operations/StaticInjection/SynchronousCondenser.json",
  "Operations/StaticInjection/ThermalMultiStart.json",
  "Operations/StaticInjection/ThermalStandard.json",
  "Operations/SupplementalAttributes/CombinedCycleBlock.json",
  "Operations/SupplementalAttributes/CombinedCycleFractional.json",
  "Operations/SupplementalAttributes/FixedForcedOutage.json",
  "Operations/SupplementalAttributes/GeometricDistributionForcedOutage.json",
  "Operations/SupplementalAttributes/HydroPowerPlant.json",
  "Operations/SupplementalAttributes/ImpedanceCorrectionData.json",
  "Operations/SupplementalAttributes/PlannedOutage.json",
  "Operations/SupplementalAttributes/RenewablePowerPlant.json",
  "Operations/SupplementalAttributes/Substation.json",
  "Operations/SupplementalAttributes/ThermalPowerPlant.json",
  "Operations/common.json",
  "TimeSeries/Deterministic.json",
  "TimeSeries/DeterministicSingleTimeSeries.json",
  "TimeSeries/NonSequentialTimeSeries.json",
  "TimeSeries/Probabilistic.json",
  "TimeSeries/Scenarios.json",
  "TimeSeries/SingleTimeSeries.json",
  "TimeSeries/TimeSeriesAssociation.json",
  "TimeSeries/common.json",
];

export default defineConfig({
  infrastructure_core: {
    input: {
      target: join(SCHEMA_DIR, "openapi-infrastructure-core.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/infrastructure_core/models.ts",
      client: "zod",
      mode: "single",
    },
  },
  core: {
    input: {
      target: join(SCHEMA_DIR, "openapi-core.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/core/models.ts",
      client: "zod",
      mode: "single",
    },
  },
  operations: {
    input: {
      target: join(SCHEMA_DIR, "openapi-operations.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/operations/models.ts",
      client: "zod",
      mode: "single",
    },
  },
  investments: {
    input: {
      target: join(SCHEMA_DIR, "openapi-investments.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/investments/models.ts",
      client: "zod",
      mode: "single",
    },
  },
  dynamics: {
    input: {
      target: join(SCHEMA_DIR, "openapi-dynamics.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/dynamics/models.ts",
      client: "zod",
      mode: "single",
    },
  },
  timeseries: {
    input: {
      target: join(SCHEMA_DIR, "openapi-timeseries.json"),
      parserOptions: {
        externalRefs: { allow: EXTERNAL_REFS_ALLOW },
      },
    },
    output: {
      target: "src/timeseries/models.ts",
      client: "zod",
      mode: "single",
    },
  },
});
