# generated by datamodel-codegen:
#   filename:  openapi-dynamics.json

from __future__ import annotations
from power_openapi_models.core.models import DbdPnts, FdbdPnts, MinMax
from power_openapi_models.core.models import DbdPnts, FdbdPnts, MinMax
from pydantic import BaseModel, Field


class ActiveRenewableControllerAB(BaseModel):
    id: int
    bus_control: int
    from_branch_control: int
    to_branch_control: int
    branch_id_control: int
    Freq_Flag: bool
    K_pg: float
    K_ig: float
    T_p: float
    fdbd_pnts: FdbdPnts
    fe_lim: MinMax
    P_lim: MinMax
    T_g: float
    D_dn: float
    D_up: float
    dP_lim: MinMax
    P_lim_inner: MinMax
    T_pord: float | None = None
    P_ref: float | None = 1.0


class RECurrentControlB(BaseModel):
    id: int
    Q_Flag: bool
    PQ_Flag: bool
    Vdip_lim: MinMax
    T_rv: float
    dbd_pnts: DbdPnts
    K_qv: float
    Iqinj_lim: MinMax
    V_ref0: float
    K_vp: float
    K_vi: float
    T_iq: float
    I_max: float


class ReactiveRenewableControllerAB(BaseModel):
    id: int
    bus_control: int
    from_branch_control: int
    to_branch_control: int
    branch_id_control: str
    VC_Flag: bool
    Ref_Flag: bool
    PF_Flag: bool
    V_Flag: bool
    T_fltr: float
    K_p: float
    K_i: float
    T_ft: float
    T_fv: float
    V_frz: float
    R_c: float
    X_c: float
    K_c: float
    e_lim: MinMax
    dbd_pnts: DbdPnts
    Q_lim: MinMax
    T_p: float
    Q_lim_inner: MinMax
    V_lim: MinMax
    K_qp: float
    K_qi: float
    Q_ref: float | None = 1.0
    V_ref: float | None = 1.0


class RenewableEnergyConverterTypeA(BaseModel):
    id: int
    T_g: float
    Rrpwr: float
    Brkpt: float
    Zerox: float
    Lvpl1: float
    Vo_lim: float
    Lv_pnts: MinMax
    Io_lim: float
    T_fltr: float
    K_hv: float
    Iqr_lims: MinMax
    Accel: float
    Lvpl_sw: bool
    Q_ref: float | None = 1.0
    R_source: float | None = 0.0
    X_source: float | None = 100000.0


class RoundRotorMachine(BaseModel):
    id: int
    R: float
    Td0_p: float
    Td0_pp: float
    Tq0_p: float
    Tq0_pp: float
    Xd: float
    Xq: float
    Xd_p: float
    Xq_p: float
    Xd_pp: float
    Xl: float
    Se: list[float] = Field(
        ...,
        description="this is meant to be a tuple, should we do this another way?",
        max_length=2,
        min_length=2,
    )
    gamma_d1: float = Field(..., description="Do not modify")
    gamma_q1: float = Field(..., description="Do not modify")
    gamma_d2: float = Field(..., description="Do not modify")
    gamma_q2: float = Field(..., description="Do not modify")
    gamma_qd: float = Field(..., description="Do not modify")


class SEXS(BaseModel):
    id: int
    Ta_Tb: float
    Tb: float
    K: float
    Te: float
    V_lim: MinMax
    V_ref: float | None = 1.0


class SteamTurbineGov1(BaseModel):
    id: int
    R: float
    T1: float
    valve_position_limits: MinMax
    T2: float
    T3: float
    D_T: float
    DB_h: float
    DB_l: float
    T_rate: float
    P_ref: float | None = None
