// @generated by codegen/rust. Do not edit.
//! The `investments` SiennaSchemas spec.
pub use crate::generated::{
    AggregateTransportTechnology, AverageRateCurve, CapacityReserveMargin, CapitalCost, CarbonCaps,
    CarbonTax, ChargeDischarge, ColocatedSupplyStorageTechnology, CostCurve, DemandRequirement,
    DemandSideTechnology, EnergyShareRequirements, ExistingDevices, FuelCurve, FunctionData,
    GenericOperationCost, HourlyMatching, HydroGenerationCost, InOut, IncrementalCurve,
    InputOutputCurve, LinearFunctionData, MaximumCapacityRequirements, MinMax, MinMaxByKey,
    MinimumCapacityRequirements, NodalACTransportTechnology, NodalHVDCTransportTechnology,
    OutageFactors, PiecewiseLinearData, PiecewiseStepData, PortfolioFinancialData, PrimeMovers,
    ProductionVariableCostCurve, QuadraticFunctionData, RenewableGenerationCost,
    RequirementAssociation, RetirementPotential, RetrofitPotential, StartUpStages,
    StorageCapitalCost, StorageCost, StorageTech, StorageTechnology, SupplyTechnology,
    TechnologyFinancialData, ThermalFuels, ThermalGenerationCost, TimeSeriesAverageRateCurve,
    TimeSeriesIncrementalCurve, TimeSeriesInputOutputCurve, TimeSeriesLinearFunctionData,
    TimeSeriesPiecewiseLinearData, TimeSeriesPiecewiseStepData, TimeSeriesQuadraticFunctionData,
    TopologyMapping, UnitSystem, UpDown, ValueCurve, XYCoords,
};
