# generated by datamodel-codegen:
#   filename:  openapi-investments.json

from __future__ import annotations
from power_openapi_models.core.models import (
    CapitalCost,
    GenericOperationCost,
    InOut,
    MinMax,
    MinMaxByKey,
    OutageFactors,
    PrimeMovers,
    ProductionVariableCostCurve,
    StorageCapitalCost,
    StorageCost,
    StorageTech,
    ThermalFuels,
    UpDown,
    ValueCurve,
)
from pydantic import BaseModel, Field


class TechnologyFinancialData(BaseModel):
    capital_recovery_period: int = Field(
        ...,
        description="Period over which capital costs are recovered for net present value calculations. Units: yr.",
    )
    technology_base_year: int = Field(
        ..., description="Base year for technology cost data used in NPV calculations."
    )
    debt_fraction: float = Field(
        ..., description="Fraction of capital costs financed through debt. Units: 1."
    )
    debt_rate: float = Field(..., description="Interest rate on debt financing. Units: 1.")
    return_on_equity: float = Field(
        ..., description="Required rate of return on equity financing. Units: 1."
    )
    tax_rate: float = Field(..., description="Tax rate applied to equity returns. Units: 1.")


class CapacityReserveMargin(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    capacity_reserve_fraction: float | None = Field(
        0.0,
        description="Capacity reserve requirements, represented as a fraction of peak demand in a region. Units: 1.",
    )


class CarbonCaps(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    max_tons_mwh: float | None = Field(
        100000000, description="Emission limit in terms of rate. Units: Mt/MWh."
    )
    max_mtons: float | None = Field(
        None, description="Emission limit in absolute values (million tonnes). Units: Mt."
    )


class CarbonTax(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    tax_dollars_per_ton: float | None = Field(
        0.0,
        description="Cost penalty per ton of CO2 emitted by technologies in the eligible regions during the target year. Units: USD/t.",
    )


class ColocatedSupplyStorageTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool | None = Field(
        None,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    region: list[int] | None = Field(
        None, description="Location where the component applies. Can be a zone or node."
    )
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )
    supply_technology: int = Field(
        ...,
        description="The ID of the underlying supply technology (e.g., wind or solar) co-located with storage.",
    )
    storage_technology: int = Field(
        ...,
        description="The ID of the underlying storage technology co-located with the supply technology.",
    )
    inverter_capacity_limits: MinMax | None = Field(
        None, description="Limits on inverter capacity. Units: MW."
    )
    capital_costs_inverter: CapitalCost = Field(
        ...,
        description="Capital and interconnection cost for investing in inverter capacity (capital cost in USD/MW).",
    )
    operation_costs_inverter: ProductionVariableCostCurve = Field(
        ...,
        description="Operational costs for using inverter in co-located systems. Units: USD/MWh.",
    )
    inverter_efficiency: float = Field(
        ..., description="Efficiency of AC to DC conversion of inverter. Units: 1."
    )
    inverter_supply_ratio: float = Field(
        ..., description="Ratio of generation capacity to grid connection capacity. Units: 1."
    )


class DemandRequirement(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool | None = Field(
        True,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    conformity: str | None = Field(
        "UNDEFINED",
        description="Indicator of how the demand requirement should conform to the load profile of existing technologies in the system. Should only be used for new demand requirements.",
    )
    growth_rate: float | None = Field(
        0.0,
        description="The annual growth rate of the demand requirement, used to scale present-day loads into future projections. Should only be used for conforming loads. Units: 1.",
    )
    new_demand_mw: float | None = Field(
        0.0,
        description="The value of the peak demand to be used for new DemandRequirements. Units: MW.",
    )
    new_construction_year: int | None = Field(
        2020,
        description="The year in which the new demand requirement will be installed. Should only be used for new demand requirements.",
    )
    region: list[int] | None = Field(
        None, description="Location where the component applies. Can be a zone or node."
    )
    value_of_lost_load: float | None = Field(
        None, description="Value of unserved load. Units: USD/MWh."
    )
    unserved_demand_curve: ValueCurve | None = Field(
        None,
        description="Piecewise curve to scale the cost of unserved load based on the value of lost load. Units: USD/MWh.",
    )


class DemandSideTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    region: list[int] | None = Field(
        None, description="Location where the component applies. Can be a zone or node."
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    technology_efficiency: float | None = Field(
        0.0,
        description="MWh of electricity per unit of output. Ex: MWh per ton of hydrogen for electrolyzers. Units: 1.",
    )
    price_per_unit: ValueCurve | None = Field(
        None,
        description="Price or value per unit of output. Ex: USD per ton of hydrogen for electrolyzers. Units: USD/t.",
    )
    min_power: float | None = Field(
        0.0,
        description="Minimum operation of demandside unit as a fraction of peak demand. Units: 1.",
    )
    peak_demand_mw: float | None = Field(0.0, description="Peak demand value in MW. Units: MW.")
    max_demand_delay: float | None = Field(
        None,
        description="Maximum number of minutes that demand can be deferred or delayed (minutes). Units: min.",
    )
    max_demand_advance: float | None = Field(
        None,
        description="Maximum number of minutes that demand can be scheduled in advance of the original schedule (minutes). Units: min.",
    )
    demand_energy_efficiency: float | None = Field(
        None,
        description="Energy efficiency associated with time shifting demand. Represents energy losses due to time shifting. Units: 1.",
    )
    shift_variable_cost: ValueCurve | None = Field(
        None,
        description="Variable operation and maintenance costs associated with flexible demand deferral/advancement. Units: USD/MWh.",
    )
    curtailment_cost: ValueCurve | None = Field(
        None, description="Energy cost of curtailed demand, USD per MWh. Units: USD/MWh."
    )
    max_demand_curtailment: float | None = Field(
        None, description="Maximum fraction of demand that can be curtailed. Units: 1."
    )


class EnergyShareRequirements(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    generation_fraction_requirement: float | None = Field(
        0.0,
        description="Fraction of total annual demand across all eligible zones that needs to be met by eligible resources. Units: 1.",
    )


class ExistingDevices(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    existing_devices: list[str] | None = Field(
        None,
        description="List of individual existing devices to map to a specific technology in the portfolio.",
    )


class HourlyMatching(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )


class MaximumCapacityRequirements(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    max_capacity_mw: float | None = Field(
        None, description="Maximum total capacity across all eligible resources. Units: MW."
    )


class MinimumCapacityRequirements(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    target_year: int | None = Field(None, description="Year in which this requirement is applied.")
    min_capacity_mw: float | None = Field(
        None, description="Minimum total capacity across all eligible resources. Units: MW."
    )


class NodalACTransportTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    start_node: int = Field(..., description="Start node for transport technology.")
    end_node: int = Field(..., description="End node for transport technology.")
    capacity_limits: MinMax | None = Field(
        None, description="Allowable capacity for a transmission line. Units: MW."
    )
    capital_costs: CapitalCost | None = Field(
        None,
        description="Capital and interconnection cost of adding new capacity to the nodal transmission line (capital cost in USD/MW).",
    )
    resistance: float | None = Field(0.0, description="Technology resistance in Ohms. Units: ohm.")
    voltage: float | None = Field(
        0.0, description="Voltage rating of transmission line. Units: kV."
    )
    unit_size: float | None = Field(
        0.0,
        description="Used for integer investment decisions. Represents the rating capacity of individual new lines. Units: MW.",
    )
    reactance: float | None = Field(0.0, description="Series reactance for a line. Units: ohm.")
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )


class NodalHVDCTransportTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    start_node: int = Field(..., description="Start node for transport technology.")
    end_node: int = Field(..., description="End node for transport technology.")
    capacity_limits: MinMax | None = Field(
        None, description="Allowable capacity for a transmission line. Units: MW."
    )
    capital_costs: CapitalCost | None = Field(
        None,
        description="Capital and interconnection cost of adding new capacity to the nodal transmission line (capital cost in USD/MW).",
    )
    line_loss: ValueCurve | None = Field(
        None,
        description="Loss model coefficients. Accepts a linear model with a constant loss and a proportional loss rate, or a Piecewise loss with N segments for different proportional losses. All terms are defined as fraction of installed nameplate capacity. Units: 1.",
    )
    unit_size: float | None = Field(
        None,
        description="Used for integer investment decisions. Represents the rating capacity of individual new lines. Units: MW.",
    )
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )


class PortfolioFinancialData(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    discount_rate: float = Field(
        0.0, description="Discount rate for financial calculations. Units: 1."
    )
    inflation_rate: float = Field(0.0, description="Inflation rate for cost adjustments. Units: 1.")
    interest_rate: float = Field(
        0.0, description="Interest rate for financing calculations. Units: 1."
    )
    base_year: int = Field(
        ...,
        description="Base economic year. All costs will be converted to a net present value in this year.",
    )


class RequirementAssociation(BaseModel):
    requirement_id: int = Field(
        ..., description="ID of the policy requirement the membership belongs to."
    )
    entity_id: int = Field(..., description="ID of the member the requirement applies to.")


class RetirementPotential(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    eligible_generators: list[str] = Field(
        ...,
        description="Names of individual generation units mapped to a technology that are eligible for retirement.",
    )
    planned_retirement_year: dict[str, int] | None = Field(
        None,
        description="Optional dictionary to indicate the year in which the forced/planned retirement will occur.",
    )
    build_year: dict[str, int] | None = Field(
        None,
        description="Optional dictionary to indicate the year in which existing generators in the base system were built.",
    )
    retirement_cost: ValueCurve = Field(
        ..., description="Cost associated with retiring the eligible generators. Units: USD/MW."
    )


class RetrofitPotential(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    eligible_generators: list[str] = Field(
        ...,
        description="Names of individual generation units mapped to this technology that can be retrofitted.",
    )
    retrofit_fraction: float | None = Field(
        1.0, description="Fraction of existing capacity that is eligible for retrofits. Units: 1."
    )
    retrofit_cost: ValueCurve = Field(
        ..., description="Cost associated with retrofitting the eligible generators. Units: USD/MW."
    )


class StorageTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    region: list[int] | None = Field(
        None, description="Location where the component applies. Can be a zone or node."
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    min_discharge_fraction: float | None = Field(
        0.0, description="Minimum discharge as a fraction of total discharge capacity. Units: 1."
    )
    prime_mover_type: PrimeMovers | None = Field("OT", description="Prime mover for generator.")
    storage_tech: StorageTech = Field(..., description="Storage Technology Type.")
    capital_costs: StorageCapitalCost | None = Field(
        None,
        description="Capital and interconnection cost for investing in a storage technology's charge, discharge, and energy capacity (charge and discharge in USD/MW, energy in USD/MWh).",
    )
    operation_costs: StorageCost | None = Field(
        None, description="Fixed and variable O&M costs for a storage technology. Units: USD/MWh."
    )
    unit_size_discharge: float | None = Field(
        0.0,
        description="Used for discrete investment decisions. Size of each unit of discharging capacity being built. Units: MW.",
    )
    unit_size_charge: float | None = Field(
        None,
        description="Used for discrete investment decisions. Unit size of charging capacity. Units: MW.",
    )
    unit_size_energy: float | None = Field(
        0.0,
        description="Used for discrete investment decisions. Size of each unit of energy capacity being built. Units: MWh.",
    )
    capacity_limits_charge: MinMax | MinMaxByKey | None = Field(
        None,
        description="Allowable installed power capacity for charging of a storage technology, given either as a single bound applied to all capacity or as a mapping from a float key (stringified) to the bound that applies at that key. Units: MW.",
    )
    capacity_limits_discharge: MinMax | MinMaxByKey | None = Field(
        None,
        description="Allowable installed power capacity for discharging of a storage technology, given either as a single bound applied to all capacity or as a mapping from a float key (stringified) to the bound that applies at that key. Units: MW.",
    )
    capacity_limits_energy: MinMax | MinMaxByKey | None = Field(
        None,
        description="Allowable installed energy capacity for a storage technology, given either as a single bound applied to all capacity or as a mapping from a float key (stringified) to the bound that applies at that key. Units: MWh.",
    )
    duration_limits: MinMax | None = Field(
        None,
        description="Minimum and maximum duration limits (energy to discharge capacity ratio) for a storage technology (minutes). Units: min.",
    )
    efficiency: InOut | None = Field(
        None,
        description="Efficiency of charging storage, fraction of total charge (in) and discharge (out) capacity. Units: 1.",
    )
    losses: float | None = Field(
        1.0, description="Self-discharge of storage (fraction of energy stored per hour). Units: 1."
    )
    lifetime: int | None = Field(
        100,
        description="Maximum number of years a technology can be active once installed. Units: yr.",
    )
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )


class SupplyTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool | None = Field(
        None,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    region: list[int] | None = Field(
        None, description="Location where the component applies. Can be a zone or node."
    )
    prime_mover_type: PrimeMovers | None = Field("OT", description="Prime mover for generator.")
    fuel: list[ThermalFuels] | None = Field(None, description="Fuel type according to IEA.")
    cofire_start_limits: dict[str, MinMax] | None = Field(
        None,
        description="Minimum and maximum blending level of each fuel during start-up process for multi-fuel generator. Units: 1.",
    )
    cofire_level_limits: dict[str, MinMax] | None = Field(
        None,
        description="Minimum and maximum blending level of each fuel during normal generation process for multi-fuel generator. Units: 1.",
    )
    capital_costs: CapitalCost | None = Field(
        None,
        description="Capital and interconnection cost for investing in a technology (capital cost in USD/MW).",
    )
    operation_costs: GenericOperationCost | None = Field(
        None, description="Fixed and variable O&M costs for a technology. Units: USD/MWh."
    )
    unit_size: float | None = Field(
        0.0,
        description="Used for discrete investment decisions. Size of each unit being built. Units: MW.",
    )
    capacity_limits: MinMax | MinMaxByKey | None = Field(
        None,
        description="Minimum and maximum allowable installed capacity for a technology, given either as a single bound applied to all capacity or as a mapping from a float key (stringified) to the bound that applies at that key. Units: MW.",
    )
    outage_factor: OutageFactors | None = Field(
        None,
        description="Planned and forced outage factors for a technology, each a fraction of total availability (the fraction of hours in a year the technology is unavailable).",
    )
    min_generation_fraction: float | None = Field(
        0.0, description="Minimum generation as a fraction of total capacity. Units: 1."
    )
    ramp_limits: UpDown | None = Field(
        None,
        description="Maximum decrease and increase in output between operation periods. Units: MW/min.",
    )
    time_limits: UpDown | None = Field(
        None,
        description="Minimum amount of time a resource has to stay in the committed or shutdown state (minutes). Units: min.",
    )
    start_fuel_mmbtu_per_mw: float | None = Field(
        0.0,
        description="Startup fuel use per MW of nameplate capacity of each generator. Units: MMBtu/MW.",
    )
    lifetime: int | None = Field(
        100,
        description="Maximum number of years a technology can be active once installed. Units: yr.",
    )
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )


class TopologyMapping(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    buses: list[str] | None = Field(
        None, description="List of buses in the base system that are associated with a zone."
    )


class AggregateTransportTechnology(BaseModel):
    id: int = Field(..., description="ID for individual component.")
    name: str = Field(..., description="Name of the component.")
    available: bool = Field(
        ...,
        description="Indicator of whether the component is connected and online (`true`) or disconnected, offline, or down (`false`).",
    )
    power_systems_type: str = Field(
        ..., description="Corresponding type to be used in PCM modeling."
    )
    start_region: int = Field(..., description="Start region for transport technology.")
    end_region: int = Field(..., description="End region for transport technology.")
    capacity_limits: MinMax | None = Field(
        None, description="Allowable capacity for a transmission line. Units: MW."
    )
    capital_costs: CapitalCost | None = Field(
        None,
        description="Capital and interconnection cost of adding new capacity to the transmission line (capital cost in USD/MW).",
    )
    line_loss: float | None = Field(
        None, description="Transmission loss for each transport technology. Units: 1."
    )
    unit_size: float | None = Field(
        None,
        description="Used for integer investment decisions. Represents the rating capacity of individual new lines. Units: MW.",
    )
    financial_data: TechnologyFinancialData = Field(
        ..., description="Struct containing relevant financial information for a technology."
    )
