# generated by datamodel-codegen:
#   filename:  openapi-operations.json
#   timestamp: 2026-03-09T22:47:35+00:00

from __future__ import annotations
from power_openapi_models.core.models import (
    ACBusType,
    ComplexNumber,
    DiscreteControlledBranchStatus,
    DiscreteControlledBranchType,
    FACTSOperationModes,
    FromTo,
    FromToToFrom,
    HydroGenerationCost,
    HydroReservoirCost,
    HydroTurbineType,
    ImportExportCost,
    InOut,
    InputOutputCurve,
    LoadConformity,
    LoadCost,
    MinMax,
    MotorLoadTechnology,
    PrimeMovers,
    PumpHydroStatus,
    RenewableGenerationCost,
    ReserveDirection,
    ReservoirDataType,
    StartUpShutDown,
    StartUpStages,
    StorageCost,
    StorageTech,
    ThermalFuels,
    ThermalGenerationCost,
    TransformerControlObjective,
    TurbinePump,
    TwoTerminalLoss,
    UpDown,
    ValueCurve,
    WindingGroupNumber,
)
from power_openapi_models.core.models import (
    ACBusType,
    ComplexNumber,
    DiscreteControlledBranchStatus,
    DiscreteControlledBranchType,
    FACTSOperationModes,
    FromTo,
    FromToToFrom,
    HydroGenerationCost,
    HydroReservoirCost,
    HydroTurbineType,
    ImportExportCost,
    InOut,
    InputOutputCurve,
    LoadConformity,
    LoadCost,
    MinMax,
    MotorLoadTechnology,
    PrimeMovers,
    PumpHydroStatus,
    RenewableGenerationCost,
    ReserveDirection,
    ReservoirDataType,
    StartUpShutDown,
    StartUpStages,
    StorageCost,
    StorageTech,
    ThermalFuels,
    ThermalGenerationCost,
    TransformerControlObjective,
    TurbinePump,
    TwoTerminalLoss,
    UpDown,
    ValueCurve,
    WindingGroupNumber,
)
from pydantic import BaseModel, Field


class ACBus(BaseModel):
    id: int
    number: int
    name: str
    available: bool
    bustype: ACBusType | None = None
    angle: float | None = None
    magnitude: float | None = None
    voltage_limits: MinMax | None = None
    base_voltage: float | None = None
    area: int | None = None
    load_zone: int | None = None


class AGC(BaseModel):
    id: int
    name: str
    available: bool
    bias: float
    K_p: float
    K_i: float
    K_d: float
    delta_t: float
    area: int | None = None
    initial_ace: float | None = 0.0


class Arc(BaseModel):
    id: int
    from_: int = Field(..., alias="from")
    to: int


class Area(BaseModel):
    id: int
    name: str
    peak_active_power: float | None = 0.0
    peak_reactive_power: float | None = 0.0
    load_response: float | None = 0.0


class AreaInterchange(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    from_area: int
    to_area: int
    flow_limits: FromToToFrom


class ConstantReserve(BaseModel):
    id: int
    name: str
    available: bool
    time_frame: float
    requirement: float
    sustained_time: float | None = 3600.0
    max_output_fraction: float | None = 1.0
    max_participation_factor: float | None = 1.0
    deployed_fraction: float | None = 0.0
    reserve_direction: ReserveDirection


class ConstantReserveGroup(BaseModel):
    id: int
    name: str
    available: bool
    requirement: float
    reserve_direction: ReserveDirection


class ConstantReserveNonSpinning(BaseModel):
    id: int
    name: str
    available: bool
    time_frame: float
    requirement: float
    sustained_time: float | None = 3600.0
    max_output_fraction: float | None = 1.0
    max_participation_factor: float | None = 1.0
    deployed_fraction: float | None = 0.0


class DCBus(BaseModel):
    area: int | None = None
    available: bool
    base_voltage: float | None = None
    id: int
    load_zone: int | None = None
    magnitude: float | None = None
    name: str
    number: float
    voltage_limits: MinMax | None = None


class DiscreteControlledACBranch(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float
    arc: int
    r: float
    x: float
    rating: float
    discrete_branch_type: DiscreteControlledBranchType | None = "OTHER"
    branch_status: DiscreteControlledBranchStatus | None = "CLOSED"


class EnergyReservoirStorage(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    prime_mover_type: PrimeMovers
    storage_technology_type: StorageTech
    storage_capacity: float
    storage_level_limits: MinMax
    initial_storage_capacity_level: float
    rating: float
    active_power: float
    input_active_power_limits: MinMax
    output_active_power_limits: MinMax
    efficiency: InOut
    reactive_power: float
    reactive_power_limits: MinMax | None = None
    base_power: float
    operation_cost: StorageCost
    conversion_factor: float | None = 1.0
    storage_target: float | None = 0.0
    cycle_limits: int | None = 10000
    dynamic_injector: None = None


class ExponentialLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    alpha: float
    beta: float
    base_power: float
    max_active_power: float
    max_reactive_power: float
    conformity: LoadConformity | None = "UNDEFINED"
    dynamic_injector: None = None


class FACTSControlDevice(BaseModel):
    name: str
    id: int
    available: bool
    bus: int
    control_mode: FACTSOperationModes | None = None
    voltage_setpoint: float
    max_shunt_current: float
    reactive_power_required: float
    dynamic_injector: None = None


class FixedAdmittance(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    Y: ComplexNumber
    dynamic_injector: None = None


class HydroDispatch(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    prime_mover_type: PrimeMovers
    active_power_limits: MinMax
    reactive_power_limits: MinMax | None = None
    ramp_limits: UpDown | None = None
    time_limits: UpDown | None = None
    base_power: float
    status: bool | None = False
    time_at_status: float | None = 10000.0
    operation_cost: HydroGenerationCost
    dynamic_injector: None = None


class HydroPumpTurbine(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    active_power_limits: MinMax
    reactive_power_limits: MinMax | None = None
    active_power_limits_pump: MinMax
    outflow_limits: MinMax | None = None
    powerhouse_elevation: float
    ramp_limits: UpDown | None = None
    time_limits: UpDown | None = None
    base_power: float
    status: PumpHydroStatus | None = "OFF"
    time_at_status: float | None = 10000.0
    operation_cost: HydroGenerationCost
    active_power_pump: float | None = 0.0
    efficiency: TurbinePump | None = {"turbine": 1.0, "pump": 1.0}
    transition_time: TurbinePump | None = {"turbine": 0.0, "pump": 0.0}
    minimum_time: TurbinePump | None = {"turbine": 0.0, "pump": 0.0}
    travel_time: float | None = None
    conversion_factor: float | None = 1.0
    must_run: bool | None = False
    prime_mover_type: PrimeMovers | None = "PS"
    dynamic_injector: None = None


class HydroReservoir(BaseModel):
    id: int
    name: str
    available: bool
    storage_level_limits: MinMax
    initial_level: float
    spillage_limits: MinMax | None = None
    inflow: float
    outflow: float
    level_targets: float | None = None
    intake_elevation: float
    head_to_volume_factor: ValueCurve
    upstream_turbines: list[int] | None = None
    downstream_turbines: list[int] | None = None
    upstream_reservoirs: list[int] | None = None
    operation_cost: HydroReservoirCost
    level_data_type: ReservoirDataType | None = "USABLE_VOLUME"


class HydroTurbine(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    active_power_limits: MinMax
    reactive_power_limits: MinMax | None = None
    base_power: float
    operation_cost: HydroGenerationCost
    powerhouse_elevation: float | None = 0.0
    ramp_limits: UpDown | None = None
    time_limits: UpDown | None = None
    outflow_limits: MinMax | None = None
    efficiency: float | None = 1.0
    turbine_type: HydroTurbineType | None = "UNKNOWN"
    conversion_factor: float | None = 1.0
    prime_mover_type: PrimeMovers | None = "HY"
    travel_time: float | None = None
    dynamic_injector: None = None


class InterconnectingConverter(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    dc_bus: int
    active_power: float
    rating: float
    active_power_limits: MinMax
    base_power: float
    dc_current: float | None = 0.0
    max_dc_current: float | None = 100000000.0
    loss_function: InputOutputCurve | None = None
    dynamic_injector: None = None


class InterruptiblePowerLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    max_active_power: float
    max_reactive_power: float
    base_power: float
    operation_cost: LoadCost
    conformity: LoadConformity | None = "UNDEFINED"
    dynamic_injector: None = None


class InterruptibleStandardLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    base_power: float
    operation_cost: LoadCost
    conformity: LoadConformity | None = "UNDEFINED"
    constant_active_power: float | None = 0.0
    constant_reactive_power: float | None = 0.0
    impedance_active_power: float | None = 0.0
    impedance_reactive_power: float | None = 0.0
    current_active_power: float | None = 0.0
    current_reactive_power: float | None = 0.0
    max_constant_active_power: float | None = 0.0
    max_constant_reactive_power: float | None = 0.0
    max_impedance_active_power: float | None = 0.0
    max_impedance_reactive_power: float | None = 0.0
    max_current_active_power: float | None = 0.0
    max_current_reactive_power: float | None = 0.0
    dynamic_injector: None = None


class Line(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float
    arc: int
    r: float
    x: float
    b: FromTo | None = None
    rating: float
    rating_b: float | None = None
    rating_c: float | None = None
    angle_limits: MinMax
    g: FromTo | None = {"from": 0.0, "to": 0.0}


class LoadZone(BaseModel):
    id: int
    name: str
    peak_active_power: float
    peak_reactive_power: float


class MonitoredLine(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float
    arc: int
    r: float
    x: float
    b: FromTo
    flow_limits: FromToToFrom
    rating: float
    rating_b: float | None = None
    rating_c: float | None = None
    angle_limits: MinMax
    g: FromTo | None = {"from": 0.0, "to": 0.0}


class MotorLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    base_power: float
    rating: float
    max_active_power: float
    reactive_power_limits: MinMax | None = None
    motor_technology: MotorLoadTechnology | None = "UNDETERMINED"
    dynamic_injector: None = None


class PhaseShiftingTransformer(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float | None = None
    arc: int
    r: float
    x: float
    primary_shunt: ComplexNumber
    tap: float
    alpha: float
    rating: float | None = None
    base_power: float
    base_voltage_primary: float | None = None
    base_voltage_secondary: float | None = None
    rating_b: float | None = None
    rating_c: float | None = None
    phase_angle_limits: MinMax | None = {"min": -3.1416, "max": 3.1416}
    control_objective: TransformerControlObjective | None = "UNDEFINED"


class PhaseShiftingTransformer3W(BaseModel):
    id: int
    name: str
    available: bool
    primary_star_arc: int
    secondary_star_arc: int
    tertiary_star_arc: int
    star_bus: int
    active_power_flow_primary: float
    reactive_power_flow_primary: float
    active_power_flow_secondary: float
    reactive_power_flow_secondary: float
    active_power_flow_tertiary: float
    reactive_power_flow_tertiary: float
    r_primary: float
    x_primary: float
    r_secondary: float
    x_secondary: float
    r_tertiary: float
    x_tertiary: float
    rating: float | None = None
    r_12: float
    x_12: float
    r_23: float
    x_23: float
    r_13: float
    x_13: float
    alpha_primary: float
    alpha_secondary: float
    alpha_tertiary: float
    base_power_12: float
    base_power_23: float
    base_power_13: float
    base_voltage_primary: float | None = None
    base_voltage_secondary: float | None = None
    base_voltage_tertiary: float | None = None
    g: float | None = 0.0
    b: float | None = 0.0
    primary_turns_ratio: float | None = 1.0
    secondary_turns_ratio: float | None = 1.0
    tertiary_turns_ratio: float | None = 1.0
    available_primary: bool | None = True
    available_secondary: bool | None = True
    available_tertiary: bool | None = True
    rating_primary: float | None = 0.0
    rating_secondary: float | None = 0.0
    rating_tertiary: float | None = 0.0
    phase_angle_limits: MinMax | None = {"min": -3.1416, "max": 3.1416}
    control_objective_primary: TransformerControlObjective | None = "UNDEFINED"
    control_objective_secondary: TransformerControlObjective | None = "UNDEFINED"
    control_objective_tertiary: TransformerControlObjective | None = "UNDEFINED"


class PowerLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    base_power: float
    max_active_power: float
    max_reactive_power: float
    conformity: LoadConformity | None = "UNDEFINED"
    dynamic_injector: None = None


class RenewableDispatch(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    prime_mover_type: PrimeMovers
    reactive_power_limits: MinMax | None = None
    power_factor: float
    operation_cost: RenewableGenerationCost
    base_power: float
    dynamic_injector: None = None


class RenewableNonDispatch(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    prime_mover_type: PrimeMovers
    power_factor: float
    base_power: float
    dynamic_injector: None = None


class ShiftablePowerLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float
    active_power_limits: MinMax
    reactive_power: float
    max_active_power: float
    max_reactive_power: float
    base_power: float
    load_balance_time_horizon: int
    operation_cost: LoadCost
    dynamic_injector: None = None


class Source(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    active_power: float | None = 0.0
    reactive_power: float | None = 0.0
    active_power_limits: MinMax | None = {"min": 0.0, "max": 0.0}
    reactive_power_limits: MinMax | None = {"min": 0.0, "max": 0.0}
    R_th: float | None = 0.0
    X_th: float | None = 0.0
    internal_voltage: float | None = 1.0
    internal_angle: float | None = 0.0
    base_power: float | None = 100.0
    operation_cost: ImportExportCost
    dynamic_injector: None = None


class StandardLoad(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    base_power: float
    constant_active_power: float | None = 0.0
    constant_reactive_power: float | None = 0.0
    impedance_active_power: float | None = 0.0
    impedance_reactive_power: float | None = 0.0
    current_active_power: float | None = 0.0
    current_reactive_power: float | None = 0.0
    max_constant_active_power: float | None = 0.0
    max_constant_reactive_power: float | None = 0.0
    max_impedance_active_power: float | None = 0.0
    max_impedance_reactive_power: float | None = 0.0
    max_current_active_power: float | None = 0.0
    max_current_reactive_power: float | None = 0.0
    conformity: LoadConformity | None = "UNDEFINED"
    dynamic_injector: None = None


class SwitchedAdmittance(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    Y: ComplexNumber
    initial_status: list[int] | None = None
    number_of_steps: list[int] | None = None
    Y_increase: list[ComplexNumber] | None = None
    admittance_limits: MinMax | None = {"min": 1.0, "max": 1.0}
    dynamic_injector: None = None


class SynchronousCondenser(BaseModel):
    id: int
    name: str
    available: bool
    bus: int
    reactive_power: float
    rating: float
    reactive_power_limits: MinMax | None = None
    base_power: float
    active_power_losses: float | None = 0.0
    dynamic_injector: None = None


class TModelHVDCLine(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    arc: int
    r: float
    l: float
    c: float
    active_power_limits_from: MinMax
    active_power_limits_to: MinMax


class TapTransformer(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float
    arc: int
    r: float
    x: float
    primary_shunt: ComplexNumber
    tap: float
    rating: float | None = None
    base_power: float
    base_voltage_primary: float | None = None
    base_voltage_secondary: float | None = None
    rating_b: float | None = None
    rating_c: float | None = None
    winding_group_number: WindingGroupNumber | None = "UNDEFINED"
    control_objective: TransformerControlObjective | None = "UNDEFINED"


class ThermalMultiStart(BaseModel):
    id: int
    name: str
    available: bool
    status: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    prime_mover_type: PrimeMovers
    fuel: ThermalFuels
    active_power_limits: MinMax
    reactive_power_limits: MinMax | None = None
    ramp_limits: UpDown | None = None
    power_trajectory: StartUpShutDown | None = None
    time_limits: UpDown | None = None
    start_time_limits: StartUpStages | None = None
    start_types: int
    operation_cost: ThermalGenerationCost
    base_power: float
    time_at_status: float | None = 10000.0
    must_run: bool | None = False
    dynamic_injector: None = None


class ThermalStandard(BaseModel):
    id: int
    name: str
    available: bool
    status: bool
    bus: int
    active_power: float
    reactive_power: float
    rating: float
    active_power_limits: MinMax
    reactive_power_limits: MinMax | None = None
    ramp_limits: UpDown | None = None
    operation_cost: ThermalGenerationCost
    base_power: float
    time_limits: UpDown | None = None
    must_run: bool | None = Field(False, title="Must Run")
    prime_mover_type: PrimeMovers | None = "OT"
    fuel_type: ThermalFuels | None = "OTHER"
    time_at_status: float | None = 10000.0
    dynamic_injector: None = None


class Transformer2W(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    reactive_power_flow: float
    arc: int
    r: float
    x: float
    primary_shunt: ComplexNumber
    rating: float | None = None
    base_power: float
    base_voltage_primary: float | None = None
    base_voltage_secondary: float | None = None
    rating_b: float | None = None
    rating_c: float | None = None
    winding_group_number: WindingGroupNumber | None = "UNDEFINED"


class Transformer3W(BaseModel):
    id: int
    name: str
    available: bool
    primary_star_arc: int
    secondary_star_arc: int
    tertiary_star_arc: int
    star_bus: int
    active_power_flow_primary: float
    reactive_power_flow_primary: float
    active_power_flow_secondary: float
    reactive_power_flow_secondary: float
    active_power_flow_tertiary: float
    reactive_power_flow_tertiary: float
    r_primary: float
    x_primary: float
    r_secondary: float
    x_secondary: float
    r_tertiary: float
    x_tertiary: float
    rating: float | None = None
    r_12: float
    x_12: float
    r_23: float
    x_23: float
    r_13: float
    x_13: float
    base_power_12: float
    base_power_23: float
    base_power_13: float
    base_voltage_primary: float | None = None
    base_voltage_secondary: float | None = None
    base_voltage_tertiary: float | None = None
    g: float | None = 0.0
    b: float | None = 0.0
    primary_turns_ratio: float | None = 1.0
    secondary_turns_ratio: float | None = 1.0
    tertiary_turns_ratio: float | None = 1.0
    available_primary: bool | None = True
    available_secondary: bool | None = True
    available_tertiary: bool | None = True
    rating_primary: float | None = 0.0
    rating_secondary: float | None = 0.0
    rating_tertiary: float | None = 0.0
    primary_group_number: WindingGroupNumber | None = "UNDEFINED"
    secondary_group_number: WindingGroupNumber | None = "UNDEFINED"
    tertiary_group_number: WindingGroupNumber | None = "UNDEFINED"
    control_objective_primary: TransformerControlObjective | None = "UNDEFINED"
    control_objective_secondary: TransformerControlObjective | None = "UNDEFINED"
    control_objective_tertiary: TransformerControlObjective | None = "UNDEFINED"


class TwoTerminalGenericHVDCLine(BaseModel):
    id: int
    name: str
    available: bool
    active_power_flow: float
    arc: int
    active_power_limits_from: MinMax
    active_power_limits_to: MinMax
    reactive_power_limits_from: MinMax
    reactive_power_limits_to: MinMax
    loss: TwoTerminalLoss | None = None


class TwoTerminalLCCLine(BaseModel):
    id: int
    name: str
    available: bool
    arc: int
    active_power_flow: float
    r: float
    transfer_setpoint: float
    scheduled_dc_voltage: float
    rectifier_bridges: int
    rectifier_delay_angle_limits: MinMax
    rectifier_rc: float
    rectifier_xc: float
    rectifier_base_voltage: float
    inverter_bridges: int
    inverter_extinction_angle_limits: MinMax
    inverter_rc: float
    inverter_xc: float
    inverter_base_voltage: float
    power_mode: bool | None = True
    switch_mode_voltage: float | None = 0.0
    compounding_resistance: float | None = 0.0
    min_compounding_voltage: float | None = 0.0
    rectifier_transformer_ratio: float | None = 1.0
    rectifier_tap_setting: float | None = 1.0
    rectifier_tap_limits: MinMax | None = {"min": 0.51, "max": 1.5}
    rectifier_tap_step: float | None = 0.00625
    rectifier_delay_angle: float | None = 0.0
    rectifier_capacitor_reactance: float | None = 0.0
    inverter_transformer_ratio: float | None = 1.0
    inverter_tap_setting: float | None = 1.0
    inverter_tap_limits: MinMax | None = {"min": 0.51, "max": 1.5}
    inverter_tap_step: float | None = 0.0625
    inverter_extinction_angle: float | None = 0.0
    inverter_capacitor_reactance: float | None = 0.0
    active_power_limits_from: MinMax | None = {"min": 0.0, "max": 0.0}
    active_power_limits_to: MinMax | None = {"min": 0.0, "max": 0.0}
    reactive_power_limits_from: MinMax | None = {"min": 0.0, "max": 0.0}
    reactive_power_limits_to: MinMax | None = {"min": 0.0, "max": 0.0}
    loss: TwoTerminalLoss | None = {
        "curve_type": "INPUT_OUTPUT",
        "function_data": {
            "function_type": "LINEAR",
            "constant_term": 0,
            "proportional_term": 0,
        },
        "input_at_zero": 0,
    }


class TwoTerminalVSCLine(BaseModel):
    id: int
    name: str
    available: bool
    arc: int
    active_power_flow: float
    rating: float
    active_power_limits_from: MinMax
    active_power_limits_to: MinMax
    g: float | None = 0.0
    dc_current: float | None = 0.0
    reactive_power_from: float | None = 0.0
    dc_voltage_control_from: bool | None = True
    ac_voltage_control_from: bool | None = True
    dc_setpoint_from: float | None = 0.0
    ac_setpoint_from: float | None = 1.0
    converter_loss_from: InputOutputCurve | None = {
        "curve_type": "INPUT_OUTPUT",
        "function_data": {
            "function_type": "LINEAR",
            "constant_term": 0,
            "proportional_term": 0,
        },
        "input_at_zero": 0,
    }
    max_dc_current_from: float | None = 100000000.0
    rating_from: float | None = 100000000.0
    reactive_power_limits_from: MinMax | None = {"min": 0.0, "max": 0.0}
    power_factor_weighting_fraction_from: float | None = 1.0
    voltage_limits_from: MinMax | None = {"min": 0.0, "max": 999.9}
    reactive_power_to: float | None = 0.0
    dc_voltage_control_to: bool | None = True
    ac_voltage_control_to: bool | None = True
    dc_setpoint_to: float | None = 0.0
    ac_setpoint_to: float | None = 1.0
    converter_loss_to: InputOutputCurve | None = {
        "curve_type": "INPUT_OUTPUT",
        "function_data": {
            "function_type": "LINEAR",
            "constant_term": 0,
            "proportional_term": 0,
        },
        "input_at_zero": 0,
    }
    max_dc_current_to: float | None = 100000000.0
    rating_to: float | None = 100000000.0
    reactive_power_limits_to: MinMax | None = {"min": 0.0, "max": 0.0}
    power_factor_weighting_fraction_to: float | None = 1.0
    voltage_limits_to: MinMax | None = {"min": 0.0, "max": 999.9}


class VariableReserve(BaseModel):
    id: int
    name: str
    available: bool
    time_frame: float
    requirement: float
    sustained_time: float | None = 3600.0
    max_output_fraction: float | None = 1.0
    max_participation_factor: float | None = 1.0
    deployed_fraction: float | None = 0.0
    reserve_direction: ReserveDirection


class VariableReserveNonSpinning(BaseModel):
    id: int
    name: str
    available: bool
    time_frame: float
    requirement: float
    sustained_time: float | None = 14400.0
    max_output_fraction: float | None = 1.0
    max_participation_factor: float | None = 1.0
    deployed_fraction: float | None = 0.0
