/**
 * Generated by orval 🍺
 * Do not edit manually.
 * InfrastructureCoreOpenAPIModels
 * Domain-neutral shared types: the unit convention, the function-data family, and the value shapes and supplemental attributes that carry no power semantics. Consumed by the data layer and the time series store, neither of which should inherit power-specific definitions.
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';

export const UnitSystem = zod.enum(['COMPONENT_BASE', 'NATURAL_UNITS']).describe('Unit basis a stored value is expressed in. COMPONENT_BASE: per-unit against a base the component records itself. NATURAL_UNITS: the quantity\'s own physical unit. No system-wide option: a value per-unitized against a shared base records that base on the component and rides as COMPONENT_BASE. Used in three scopes, each read against its own record rather than a document-wide table: a component\'s own `power_units` (against that component\'s `base_power`), a cost payload\'s own `power_units` (e.g. `CostCurve`, against the owning component\'s `base_power`), and a time series association\'s own `unit_system` (governing only that one series).')

export type UnitSystem = zod.input<typeof UnitSystem>;
export type UnitSystemOutput = zod.output<typeof UnitSystem>;

export const ComplexNumber = zod.object({
  "real": zod.number().optional(),
  "imag": zod.number().optional()
}).describe('A complex number, given as its `real` and `imag` parts.')

export type ComplexNumber = zod.input<typeof ComplexNumber>;
export type ComplexNumberOutput = zod.output<typeof ComplexNumber>;

export const XYCoords = zod.object({
  "x": zod.number(),
  "y": zod.number()
}).describe('A single point, given as its `x` and `y` coordinates.')

export type XYCoords = zod.input<typeof XYCoords>;
export type XYCoordsOutput = zod.output<typeof XYCoords>;

export const MinMax = zod.object({
  "max": zod.number().optional(),
  "min": zod.number().optional()
}).describe('A pair of values bounding a quantity from below (`min`) and from above (`max`).')

export type MinMax = zod.input<typeof MinMax>;
export type MinMaxOutput = zod.output<typeof MinMax>;

export const UpDown = zod.object({
  "down": zod.number(),
  "up": zod.number()
}).describe('A pair of values, one for the upward (`up`) and one for the downward (`down`) direction of a quantity.')

export type UpDown = zod.input<typeof UpDown>;
export type UpDownOutput = zod.output<typeof UpDown>;

export const InOut = zod.object({
  "in": zod.number().optional(),
  "out": zod.number().optional()
}).describe('A pair of values, one for the inbound (`in`) and one for the outbound (`out`) direction of a quantity.')

export type InOut = zod.input<typeof InOut>;
export type InOutOutput = zod.output<typeof InOut>;

export const FromTo = zod.object({
  "from": zod.number().optional(),
  "to": zod.number().optional()
}).describe('A pair of values, one at the `from` end and one at the `to` end of a directed edge.')

export type FromTo = zod.input<typeof FromTo>;
export type FromToOutput = zod.output<typeof FromTo>;

export const FromToToFrom = zod.object({
  "from_to": zod.number().optional(),
  "to_from": zod.number().optional()
}).describe('A pair of values for a directed edge, one for each orientation: `from_to` and `to_from`. The two are carried separately because the quantity need not be equal in the two directions.')

export type FromToToFrom = zod.input<typeof FromToToFrom>;
export type FromToToFromOutput = zod.output<typeof FromToToFrom>;

export const functionDataOneFunctionTypeDefault = `LINEAR`;
export const functionDataTwoFunctionTypeDefault = `QUADRATIC`;
export const functionDataThreeFunctionTypeDefault = `PIECEWISE_LINEAR`;
export const functionDataFourFunctionTypeDefault = `PIECEWISE_STEP`;
export const functionDataFiveFunctionTypeDefault = `TIME_SERIES_LINEAR`;
export const functionDataSixFunctionTypeDefault = `TIME_SERIES_QUADRATIC`;
export const functionDataSevenFunctionTypeDefault = `TIME_SERIES_PIECEWISE_LINEAR`;
export const functionDataEightFunctionTypeDefault = `TIME_SERIES_PIECEWISE_STEP`;
export const FunctionData = zod.union([zod.object({
  "constant_term": zod.number(),
  "function_type": zod.literal("LINEAR").default(functionDataOneFunctionTypeDefault),
  "proportional_term": zod.number()
}).describe('Data for a linear function `f(x) = proportional_term * x + constant_term`.'),zod.object({
  "constant_term": zod.number(),
  "function_type": zod.literal("QUADRATIC").default(functionDataTwoFunctionTypeDefault),
  "proportional_term": zod.number(),
  "quadratic_term": zod.number()
}).describe('Data for a quadratic function `f(x) = quadratic_term * x^2 + proportional_term * x + constant_term`. A non-negative `quadratic_term` makes the function convex.'),zod.object({
  "function_type": zod.literal("PIECEWISE_LINEAR").default(functionDataThreeFunctionTypeDefault),
  "points": zod.array(zod.object({
  "x": zod.number(),
  "y": zod.number()
}).describe('A single point, given as its `x` and `y` coordinates.'))
}).describe('Data for a piecewise linear function defined by (x, y) points and interpolated linearly between consecutive ones. The y values are absolute values at each x, not per-segment slopes; use `PiecewiseStepData` when the data gives per-segment rates. Points run in ascending x order, and two of them define one segment.'),zod.object({
  "function_type": zod.literal("PIECEWISE_STEP").default(functionDataFourFunctionTypeDefault),
  "x_coords": zod.array(zod.number()),
  "y_coords": zod.array(zod.number())
}).describe('Data for a step function, constant on each segment, defined by the x coordinates of the segment endpoints and one y value per segment. The y values are per-segment rates, not absolute values; use `PiecewiseLinearData` when the data gives a value at each point. `x_coords` ascends and holds at least two entries, and `y_coords` holds exactly one fewer.'),zod.object({
  "function_type": zod.literal("TIME_SERIES_LINEAR").default(functionDataFiveFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `LinearFunctionData`. In place of inline coefficients it carries `association_id`, referencing a stored series that supplies them at each step; use it when the coefficients change over time.'),zod.object({
  "function_type": zod.literal("TIME_SERIES_QUADRATIC").default(functionDataSixFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `QuadraticFunctionData`. In place of inline coefficients it carries `association_id`, referencing a stored series that supplies them at each step; use it when the coefficients change over time.'),zod.object({
  "function_type": zod.literal("TIME_SERIES_PIECEWISE_LINEAR").default(functionDataSevenFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `PiecewiseLinearData`. In place of an inline point table it carries `association_id`, referencing a stored series that supplies one at each step; use it when the points change over time.'),zod.object({
  "function_type": zod.literal("TIME_SERIES_PIECEWISE_STEP").default(functionDataEightFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `PiecewiseStepData`. In place of inline coordinate vectors it carries `association_id`, referencing a stored series that supplies them at each step; use it when the segments change over time.')]).describe('Raw mathematical data defining a function `f(x)` — coefficients or point tables with no units or interpretation attached. `function_type` selects the shape: linear, quadratic, piecewise linear through (x, y) points, or piecewise constant between x endpoints. What `x` and `y` stand for is supplied by whatever wraps this, and the `TIME_SERIES_*` variants hold a reference to a stored series in place of the numbers.')

export type FunctionData = zod.input<typeof FunctionData>;
export type FunctionDataOutput = zod.output<typeof FunctionData>;

export const linearFunctionDataFunctionTypeDefault = `LINEAR`;
export const LinearFunctionData = zod.object({
  "constant_term": zod.number(),
  "function_type": zod.enum(['LINEAR']).default(linearFunctionDataFunctionTypeDefault),
  "proportional_term": zod.number()
}).describe('Data for a linear function `f(x) = proportional_term * x + constant_term`.')

export type LinearFunctionData = zod.input<typeof LinearFunctionData>;
export type LinearFunctionDataOutput = zod.output<typeof LinearFunctionData>;

export const quadraticFunctionDataFunctionTypeDefault = `QUADRATIC`;
export const QuadraticFunctionData = zod.object({
  "constant_term": zod.number(),
  "function_type": zod.enum(['QUADRATIC']).default(quadraticFunctionDataFunctionTypeDefault),
  "proportional_term": zod.number(),
  "quadratic_term": zod.number()
}).describe('Data for a quadratic function `f(x) = quadratic_term * x^2 + proportional_term * x + constant_term`. A non-negative `quadratic_term` makes the function convex.')

export type QuadraticFunctionData = zod.input<typeof QuadraticFunctionData>;
export type QuadraticFunctionDataOutput = zod.output<typeof QuadraticFunctionData>;

export const piecewiseLinearDataFunctionTypeDefault = `PIECEWISE_LINEAR`;
export const PiecewiseLinearData = zod.object({
  "function_type": zod.enum(['PIECEWISE_LINEAR']).default(piecewiseLinearDataFunctionTypeDefault),
  "points": zod.array(zod.object({
  "x": zod.number(),
  "y": zod.number()
}).describe('A single point, given as its `x` and `y` coordinates.'))
}).describe('Data for a piecewise linear function defined by (x, y) points and interpolated linearly between consecutive ones. The y values are absolute values at each x, not per-segment slopes; use `PiecewiseStepData` when the data gives per-segment rates. Points run in ascending x order, and two of them define one segment.')

export type PiecewiseLinearData = zod.input<typeof PiecewiseLinearData>;
export type PiecewiseLinearDataOutput = zod.output<typeof PiecewiseLinearData>;

export const piecewiseStepDataFunctionTypeDefault = `PIECEWISE_STEP`;
export const PiecewiseStepData = zod.object({
  "function_type": zod.enum(['PIECEWISE_STEP']).default(piecewiseStepDataFunctionTypeDefault),
  "x_coords": zod.array(zod.number()),
  "y_coords": zod.array(zod.number())
}).describe('Data for a step function, constant on each segment, defined by the x coordinates of the segment endpoints and one y value per segment. The y values are per-segment rates, not absolute values; use `PiecewiseLinearData` when the data gives a value at each point. `x_coords` ascends and holds at least two entries, and `y_coords` holds exactly one fewer.')

export type PiecewiseStepData = zod.input<typeof PiecewiseStepData>;
export type PiecewiseStepDataOutput = zod.output<typeof PiecewiseStepData>;

export const timeSeriesLinearFunctionDataFunctionTypeDefault = `TIME_SERIES_LINEAR`;
export const TimeSeriesLinearFunctionData = zod.object({
  "function_type": zod.enum(['TIME_SERIES_LINEAR']).default(timeSeriesLinearFunctionDataFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `LinearFunctionData`. In place of inline coefficients it carries `association_id`, referencing a stored series that supplies them at each step; use it when the coefficients change over time.')

export type TimeSeriesLinearFunctionData = zod.input<typeof TimeSeriesLinearFunctionData>;
export type TimeSeriesLinearFunctionDataOutput = zod.output<typeof TimeSeriesLinearFunctionData>;

export const timeSeriesQuadraticFunctionDataFunctionTypeDefault = `TIME_SERIES_QUADRATIC`;
export const TimeSeriesQuadraticFunctionData = zod.object({
  "function_type": zod.enum(['TIME_SERIES_QUADRATIC']).default(timeSeriesQuadraticFunctionDataFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `QuadraticFunctionData`. In place of inline coefficients it carries `association_id`, referencing a stored series that supplies them at each step; use it when the coefficients change over time.')

export type TimeSeriesQuadraticFunctionData = zod.input<typeof TimeSeriesQuadraticFunctionData>;
export type TimeSeriesQuadraticFunctionDataOutput = zod.output<typeof TimeSeriesQuadraticFunctionData>;

export const timeSeriesPiecewiseLinearDataFunctionTypeDefault = `TIME_SERIES_PIECEWISE_LINEAR`;
export const TimeSeriesPiecewiseLinearData = zod.object({
  "function_type": zod.enum(['TIME_SERIES_PIECEWISE_LINEAR']).default(timeSeriesPiecewiseLinearDataFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `PiecewiseLinearData`. In place of an inline point table it carries `association_id`, referencing a stored series that supplies one at each step; use it when the points change over time.')

export type TimeSeriesPiecewiseLinearData = zod.input<typeof TimeSeriesPiecewiseLinearData>;
export type TimeSeriesPiecewiseLinearDataOutput = zod.output<typeof TimeSeriesPiecewiseLinearData>;

export const timeSeriesPiecewiseStepDataFunctionTypeDefault = `TIME_SERIES_PIECEWISE_STEP`;
export const TimeSeriesPiecewiseStepData = zod.object({
  "function_type": zod.enum(['TIME_SERIES_PIECEWISE_STEP']).default(timeSeriesPiecewiseStepDataFunctionTypeDefault),
  "association_id": zod.int().describe('Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.')
}).describe('Time-series-backed variant of `PiecewiseStepData`. In place of inline coordinate vectors it carries `association_id`, referencing a stored series that supplies them at each step; use it when the segments change over time.')

export type TimeSeriesPiecewiseStepData = zod.input<typeof TimeSeriesPiecewiseStepData>;
export type TimeSeriesPiecewiseStepDataOutput = zod.output<typeof TimeSeriesPiecewiseStepData>;

export const GeographicInfo = zod.object({
  "id": zod.int(),
  "geo_json": zod.record(zod.string(), zod.unknown())
}).describe('Supplemental attribute carrying geographic information about a component as a GeoJSON object. An empty object is permitted and means no geographic information is recorded.')

export type GeographicInfo = zod.input<typeof GeographicInfo>;
export type GeographicInfoOutput = zod.output<typeof GeographicInfo>;

export const DataSource = zod.object({
  "id": zod.int(),
  "organization": zod.string().optional().describe('Publishing organization, e.g. \'U.S. Energy Information Administration\'.'),
  "retrieved_at": zod.iso.datetime({"offset":true}).describe('When the data was obtained.'),
  "dataset": zod.string().optional().describe('Dataset identifier within the publishing organization, e.g. \'EIA-860 2023, Schedule 3\'.'),
  "url": zod.string().optional().describe('URL the data was retrieved from.'),
  "version": zod.string().optional().describe('Data version or vintage, e.g. \'2023 final\'.'),
  "published_at": zod.iso.datetime({"offset":true}).nullish().describe('When the source published the data; null if unknown.'),
  "confidence": zod.string().optional().describe('Confidence qualifier, e.g. \'high\', \'medium\'.'),
  "recorded_by": zod.string().nullish().describe('User or agent that recorded the value.'),
  "fields": zod.array(zod.string()).describe('Names of the component fields this provenance record applies to.'),
  "extra": zod.record(zod.string(), zod.string()).optional().describe('Additional string-valued provenance metadata.')
}).describe('Records data provenance for a component\'s field values: which organization or dataset the data came from, the URL it was retrieved from, and when it was retrieved. Mirrors the `DataSource` supplemental attribute from the upstream data layer, with two deliberate divergences: `organization` is optional here although it is required upstream, and `extra` is narrowed from an any-valued map to a string-valued one. Linked to the entity it describes through Core/Associations/SupplementalAttributeAssociation.json with attribute_type: "DataSource".')

export type DataSource = zod.input<typeof DataSource>;
export type DataSourceOutput = zod.output<typeof DataSource>;

export const SupplementalAttributeAssociation = zod.object({
  "component_id": zod.int().describe('ID of the component the attribute describes.'),
  "component_type": zod.string().describe('Type name of the component the attribute describes. A denormalized label matching the relational mirror\'s column, used for filtering; not part of the row\'s identity, which is the `(component_id, attribute_id)` pair.'),
  "attribute_id": zod.int().describe('ID of the supplemental attribute.'),
  "attribute_type": zod.string().describe('Schema title of the referenced supplemental attribute (e.g. "EmissionsData", "GeographicInfo"). A free-form string, not an enum: new attribute types are added elsewhere in this repo continuously, and a closed enum here would go stale.')
}).describe('Links a supplemental attribute to the component it describes — the JSON form of a row in the store\'s `supplemental_attribute_associations` catalog table, field-for-field. `component_type` and `attribute_type` are denormalized labels carried for filtering and reporting, not identity: identity is the `(component_id, attribute_id)` pair. Lives in Core because either side may be a Core or an Operations type. Unlike `components`, `supplemental_attributes` is a flat, untyped array, so `attribute_type` is this record\'s only per-row type discriminator.')

export type SupplementalAttributeAssociation = zod.input<typeof SupplementalAttributeAssociation>;
export type SupplementalAttributeAssociationOutput = zod.output<typeof SupplementalAttributeAssociation>;

