# generated by datamodel-codegen:
#   filename:  openapi-investments.json

from __future__ import annotations
from power_openapi_models.core.models import (
    ACBusType,
    InOut,
    MinMax,
    PrimeMovers,
    ProductionVariableCostCurve,
    RenewableGenerationCost,
    StorageCost,
    StorageTech,
    TechnologyFinancialData,
    ThermalFuels,
    ThermalRenewableGenerationCost,
    UpDown,
    ValueCurve,
)
from pydantic import BaseModel, Field
from power_openapi_models.core.models import (
    ACBusType,
    InOut,
    MinMax,
    PrimeMovers,
    ProductionVariableCostCurve,
    RenewableGenerationCost,
    StorageCost,
    StorageTech,
    TechnologyFinancialData,
    ThermalFuels,
    ThermalRenewableGenerationCost,
    UpDown,
    ValueCurve,
)


class AggregateRetirementPotential(BaseModel):
    retirement_potential: float


class AggregateRetrofitPotential(BaseModel):
    retrofit_id: int
    retrofit_potential: float | None = "0.0"
    retrofit_fraction: float | None = Field(None, description="Units: 1.")


class AggregateTransportTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str | None = None
    start_region: int | None = None
    end_region: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = Field(None, description="Units: USD/MW.")
    line_loss: float | None = Field(None, description="Units: 1.")
    unit_size: float | None = Field(None, description="Units: MW.")
    financial_data: TechnologyFinancialData | None = None


class CapacityReserveMargin(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_regions: list[int] | None = None
    eligible_technologies: list[int] | None = None
    target_year: int | None = None
    capacity_reserve_fraction: float | None = Field("0.0", description="Units: 1.")


class CarbonCaps(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_regions: list[int] | None = None
    target_year: int | None = None
    max_tons_mwh: float | None = Field("1e8", description="Units: Mt/MWh.")
    max_mtons: float | None = Field(None, description="Units: Mt.")


class CarbonTax(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_regions: list[int] | None = None
    tax_dollars_per_ton: float | None = Field("0.0", description="Units: USD/t.")


class ColocatedSupplyStorageTechnology(BaseModel):
    name: str
    id: int | None = None
    power_systems_type: str
    base_year: int | None = None
    region: list[int] | None = None
    financial_data: TechnologyFinancialData | None = None
    available: bool
    balancing_topology: str | None = None
    capital_costs_solar: ValueCurve | None = Field(None, description="Units: USD/MW.")
    operation_costs_solar: RenewableGenerationCost | None = Field(
        None, description="Units: USD/MWh."
    )
    capacity_limits_solar: MinMax | None = Field(None, description="Units: MW.")
    lifetime_solar: int | None = Field(None, description="Units: yr.")
    capital_costs_wind: ValueCurve | None = Field(None, description="Units: USD/MW.")
    operation_costs_wind: RenewableGenerationCost | None = Field(
        None, description="Units: USD/MWh."
    )
    capacity_limits_wind: MinMax | None = Field(None, description="Units: MW.")
    lifetime_wind: int | None = Field(None, description="Units: yr.")
    capital_costs_energy: ValueCurve | None = Field(None, description="Units: USD/MWh.")
    capital_costs_power: ValueCurve | None = Field(None, description="Units: USD/MW.")
    operation_costs_energy: StorageCost | None = Field(
        None, description="Units: USD/MWh."
    )
    operation_costs_power: StorageCost | None = Field(
        None, description="Units: USD/MWh."
    )
    capacity_power_limits: MinMax | None = Field(None, description="Units: MW.")
    capacity_energy_limits: MinMax | None = Field(None, description="Units: MWh.")
    duration_limits: MinMax | None = Field(None, description="Units: h.")
    efficiency_storage: InOut | None = Field(None, description="Units: 1.")
    losses_storage: float | None = Field("1.0", description="Units: 1.")
    lifetime_storage: int | None = Field("100", description="Units: yr.")
    max_inverter_capacity: float | None = Field(None, description="Units: MW.")
    min_inverter_capacity: float | None = Field(None, description="Units: MW.")
    capital_costs_inverter: ValueCurve | None = Field(
        None, description="Units: USD/MW."
    )
    operation_costs_inverter: ProductionVariableCostCurve | None = None
    inverter_efficiency: float | None = Field(None, description="Units: 1.")
    inverter_supply_ratio: float | None = None


class DemandRequirement(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str
    peak_demand_mw: float | None = Field("0.0", description="Units: MW.")
    region: list[int] | None = None
    value_of_lost_load: float | None = Field(None, description="Units: USD/MWh.")
    unserved_demand_curve: ValueCurve | None = None


class DemandSideTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    region: list[int] | None = None
    power_systems_type: str
    technology_efficiency: float | None = Field("0.0", description="Units: 1.")
    price_per_unit: ValueCurve | None = None
    min_power: float | None = Field("0.0", description="Units: MW.")
    peak_demand_mw: float | None = Field("0.0", description="Units: MW.")
    max_demand_delay: float | None = None
    max_demand_advance: float | None = None
    demand_energy_efficiency: float | None = None
    shift_variable_cost: ValueCurve | None = None
    curtailment_cost: ValueCurve | None = None
    max_demand_curtailment: float | None = None


class EnergyShareRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_regions: list[int] | None = None
    eligible_resources: list[int] | None = None
    generation_fraction_requirement: float | None = Field(
        "0.0", description="Units: 1."
    )


class ExistingCapacity(BaseModel):
    existing_technologies: list[str] | None = None


class HourlyMatching(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_resources: list[int] | None = None
    eligible_demand: list[int] | None = None


class Result(BaseModel):
    technology: str | None = None
    parameter: str | None = None
    name: str | None = None
    installations: list[float] | None = None


class InvestmentScheduleResults(BaseModel):
    start_dates: list[str] | None = None
    end_dates: list[str] | None = None
    results: list[Result] | None = None


class MaximumCapacityRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_resources: list[int]
    max_capacity_mw: float | None = Field(None, description="Units: MW.")


class MinimumCapacityRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_resources: list[int]
    min_capacity_mw: float | None = Field(None, description="Units: MW.")


class NodalACTransportTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str | None = None
    start_node: int | None = None
    end_node: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = Field(None, description="Units: USD/MW.")
    resistance: float | None = Field("0.0", description="Units: pu.")
    voltage: float | None = Field("0.0", description="Units: kV.")
    unit_size: float | None = Field("0.0", description="Units: MW.")
    reactance: float | None = Field("0.0", description="Units: pu.")
    financial_data: TechnologyFinancialData | None = None


class NodalHVDCTransportTechnology(BaseModel):
    name: str
    id: int
    available: bool
    power_systems_type: str | None = None
    start_node: int | None = None
    end_node: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = Field(None, description="Units: USD/MW.")
    line_loss: ValueCurve | None = Field(None, description="Units: 1.")
    unit_size: float | None = Field(None, description="Units: MW.")
    financial_data: TechnologyFinancialData | None = None


class Node(BaseModel):
    name: str
    id: int | None = None
    bus_type: ACBusType | None = "PQ"


class PortfolioFinancialData(BaseModel):
    name: str
    discount_rate: float = Field(..., description="Units: 1.")
    inflation_rate: float = Field(..., description="Units: 1.")
    interest_rate: float | None = Field("0.0", description="Units: 1.")
    base_year: int
    id: int | None = None


class RetirementPotential(BaseModel):
    eligible_generators: list[str] | None = None
    planned_retirement_year: dict[str, int] | None = None
    build_year: dict[str, int] | None = None


class RetrofitPotential(BaseModel):
    eligible_generators: list[str] | None = None
    uuid: str | None = None


class StorageTechnology(BaseModel):
    name: str
    region: list[int] | None = None
    id: int | None = None
    available: bool
    power_systems_type: str
    min_discharge_fraction: float | None = Field("0.0", description="Units: 1.")
    prime_mover_type: PrimeMovers | None = "OT"
    storage_tech: StorageTech | None = None
    capital_costs_energy: ValueCurve | None = Field(None, description="Units: USD/MWh.")
    capital_costs_charge: ValueCurve | None = Field(None, description="Units: USD/MW.")
    capital_costs_discharge: ValueCurve | None = Field(
        None, description="Units: USD/MW."
    )
    operation_costs: StorageCost | None = Field(None, description="Units: USD/MWh.")
    unit_size_discharge: float | None = Field("0.0", description="Units: MW.")
    unit_size_charge: float | None = Field("0.0", description="Units: MW.")
    unit_size_energy: float | None = Field("0.0", description="Units: MWh.")
    capacity_limits_charge: MinMax | None = Field(None, description="Units: MW.")
    capacity_limits_discharge: MinMax | None = Field(None, description="Units: MW.")
    capacity_limits_energy: MinMax | None = Field(None, description="Units: MWh.")
    duration_limits: MinMax | None = Field(None, description="Units: h.")
    efficiency: InOut | None = Field(None, description="Units: 1.")
    losses: float | None = Field("1.0", description="Units: 1.")
    lifetime: int | None = Field("100", description="Units: yr.")
    financial_data: TechnologyFinancialData | None = None


class SupplyTechnology(BaseModel):
    name: str
    power_systems_type: str
    region: list[int] | None = None
    id: int | None = None
    available: bool
    prime_mover_type: PrimeMovers | None = "OT"
    fuel: list[ThermalFuels] | None = None
    co2: dict[str, float] | None = Field(None, description="Units: t/MMBtu.")
    cofire_start_limits: dict[str, MinMax] | None = Field(None, description="Units: 1.")
    cofire_level_limits: dict[str, MinMax] | None = Field(None, description="Units: 1.")
    capital_costs: ValueCurve | None = Field(None, description="Units: USD/MW.")
    operation_costs: ThermalRenewableGenerationCost | None = Field(
        None, description="Units: USD/MWh."
    )
    unit_size: float | None = Field("0.0", description="Units: MW.")
    capacity_limits: MinMax | None = Field(None, description="Units: MW.")
    outage_factor: float | None = Field("1.0", description="Units: 1.")
    min_generation_fraction: float | None = Field("0.0", description="Units: 1.")
    ramp_limits: UpDown | None = Field(None, description="Units: MW/min.")
    time_limits: UpDown | None = Field(None, description="Units: h.")
    start_fuel_mmbtu_per_mw: float | None = Field("0.0", description="Units: MMBtu/MW.")
    lifetime: int | None = Field("100", description="Units: yr.")
    financial_data: TechnologyFinancialData | None = None


class TechnologyFinancialDataModel(BaseModel):
    name: str
    interest_rate: float | None = Field("0.0", description="Units: 1.")
    capital_recovery_period: int = Field(..., description="Units: yr.")
    technology_base_year: int
    id: int | None = None


class TopologyMapping(BaseModel):
    buses: list[str] | None = None
    uuid: str | None = None


class Zone(BaseModel):
    name: str
    id: int | None = None
