# generated by datamodel-codegen:
#   filename:  openapi-investments.json

from __future__ import annotations
from power_openapi_models.core.models import (
    ACBusType,
    InOut,
    MinMax,
    PrimeMovers,
    ProductionVariableCostCurve,
    RenewableGenerationCost,
    StorageCost,
    StorageTech,
    TechnologyFinancialData,
    ThermalFuels,
    ThermalGenerationCost,
    UpDown,
    ValueCurve,
)
from power_openapi_models.core.models import (
    ACBusType,
    InOut,
    MinMax,
    PrimeMovers,
    ProductionVariableCostCurve,
    RenewableGenerationCost,
    StorageCost,
    StorageTech,
    TechnologyFinancialData,
    ThermalFuels,
    ThermalGenerationCost,
    UpDown,
    ValueCurve,
)
from pydantic import BaseModel, Field


class ACTransportTechnology(BaseModel):
    name: str
    base_year: int | None = "2020"
    id: int | None = None
    available: bool
    base_power: float | None = None
    power_systems_type: str | None = None
    start_region: int | None = None
    end_region: int | None = None
    existing_line_capacity: float | None = None
    maximum_new_capacity: float | None = None
    capital_cost: ValueCurve | None = None
    line_loss: float | None = None
    resistance: float | None = "0.0"
    voltage: float | None = "0.0"
    angle_limit: float | None = "0.0"
    financial_data: int | None = None


class AggregateRetirementPotential(BaseModel):
    retirement_potential: float


class AggregateRetrofitPotential(BaseModel):
    retrofit_id: int
    retrofit_potential: float | None = "0.0"
    retrofit_fraction: float | None = None


class AggregateTransportTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str | None = None
    start_region: int | None = None
    end_region: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = None
    line_loss: float | None = None
    unit_size: float | None = None
    financial_data: TechnologyFinancialData | None = None


class CapacityReserveMargin(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_regions: list[int] | None = None
    eligible_technologies: list[int] | None = None
    target_year: int | None = None
    capacity_reserve_fraction: float | None = "0.0"


class CarbonCaps(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_regions: list[int] | None = None
    target_year: int | None = None
    max_tons_mwh: float | None = "1e8"
    max_mtons: float | None = None


class CarbonTax(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_regions: list[int] | None = None
    tax_dollars_per_ton: float | None = "0.0"


class ColocatedSupplyStorageTechnology(BaseModel):
    name: str
    id: int | None = None
    power_systems_type: str
    base_year: int | None = None
    region: list[int] | None = None
    financial_data: TechnologyFinancialData | None = None
    available: bool
    balancing_topology: str | None = None
    capital_costs_solar: ValueCurve | None = None
    operation_costs_solar: RenewableGenerationCost | None = None
    capacity_limits_solar: MinMax | None = None
    lifetime_solar: int | None = None
    capital_costs_wind: ValueCurve | None = None
    operation_costs_wind: RenewableGenerationCost | None = None
    capacity_limits_wind: MinMax | None = None
    lifetime_wind: int | None = None
    capital_costs_energy: ValueCurve | None = None
    capital_costs_power: ValueCurve | None = None
    operation_costs_energy: StorageCost | None = None
    operation_costs_power: StorageCost | None = None
    capacity_power_limits: MinMax | None = None
    capacity_energy_limits: MinMax | None = None
    duration_limits: MinMax | None = None
    efficiency_storage: InOut | None = None
    losses_storage: float | None = "1.0"
    lifetime_storage: int | None = "100"
    max_inverter_capacity: float | None = None
    min_inverter_capacity: float | None = None
    capital_costs_inverter: ValueCurve | None = None
    operation_costs_inverter: ProductionVariableCostCurve | None = None
    inverter_efficiency: float | None = None
    inverter_supply_ratio: float | None = None


class CurtailableDemandSideTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str
    voll: float | None = None
    segments: list[int] | None = None
    curtailment_cost: list[float] | None = None
    max_demand_curtailment: list[float] | None = None
    curtailment_cost_mwh: list[float] | None = None


class DemandRequirement(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str
    peak_demand_mw: float | None = "0.0"
    region: list[int] | None = None
    value_of_lost_load: float | None = None
    unserved_demand_curve: ValueCurve | None = None


class DemandSideTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    region: list[int] | None = None
    power_systems_type: str
    technology_efficiency: float | None = "0.0"
    price_per_unit: ValueCurve | None = None
    min_power: float | None = "0.0"
    peak_demand_mw: float | None = "0.0"
    max_demand_delay: float | None = None
    max_demand_advance: float | None = None
    demand_energy_efficiency: float | None = None
    shift_variable_cost: ValueCurve | None = None
    curtailment_cost: ValueCurve | None = None
    max_demand_curtailment: float | None = None


class EnergyShareRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_regions: list[int] | None = None
    eligible_resources: list[int] | None = None
    generation_fraction_requirement: float | None = "0.0"


class ExistingCapacity(BaseModel):
    existing_technologies: list[str] | None = None


class FlexibleDemandTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str
    max_demand_delay: float | None = None
    max_demand_advance: float | None = None
    demand_energy_efficiency: float | None = None
    var_cost_per_mwh: ValueCurve | None = None


class HVDCTransportTechnology(BaseModel):
    name: str
    base_year: int | None = "2020"
    id: int
    available: bool
    base_power: float | None = None
    power_systems_type: str | None = None
    start_region: int | None = None
    end_region: int | None = None
    existing_line_capacity: float | None = None
    maximum_new_capacity: float | None = None
    capital_cost: ValueCurve | None = None
    line_loss: float | None = None
    resistance: float | None = "0.0"
    voltage: float | None = "0.0"
    angle_limit: float | None = "0.0"
    financial_data: int | None = None


class HourlyMatching(BaseModel):
    name: str
    id: int | None = None
    available: bool
    eligible_resources: list[int] | None = None
    eligible_demand: list[int] | None = None


class Result(BaseModel):
    technology: str | None = None
    parameter: str | None = None
    name: str | None = None
    installations: list[float] | None = None


class InvestmentScheduleResults(BaseModel):
    start_dates: list[str] | None = None
    end_dates: list[str] | None = None
    results: list[Result] | None = None


class MaximumCapacityRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_resources: list[int]
    max_capacity_mw: float | None = None


class MinimumCapacityRequirements(BaseModel):
    name: str
    id: int | None = None
    available: bool
    target_year: int | None = None
    eligible_resources: list[int]
    min_capacity_mw: float | None = None


class NodalACTransportTechnology(BaseModel):
    name: str
    id: int | None = None
    available: bool
    power_systems_type: str | None = None
    start_node: int | None = None
    end_node: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = None
    resistance: float | None = "0.0"
    voltage: float | None = "0.0"
    unit_size: float | None = "0.0"
    reactance: float | None = "0.0"
    financial_data: TechnologyFinancialData | None = None


class NodalHVDCTransportTechnology(BaseModel):
    name: str
    id: int
    available: bool
    power_systems_type: str | None = None
    start_node: int | None = None
    end_node: int | None = None
    capacity_limits: MinMax | None = None
    capital_costs: ValueCurve | None = None
    line_loss: float | None = None
    unit_size: float | None = None
    financial_data: TechnologyFinancialData | None = None


class Node(BaseModel):
    name: str
    id: int | None = None
    bus_type: ACBusType | None = "PQ"


class PortfolioFinancialData(BaseModel):
    name: str
    discount_rate: float
    inflation_rate: float
    interest_rate: float | None = "0.0"
    base_year: int
    id: int | None = None


class RetirementPotential(BaseModel):
    eligible_generators: list[str] | None = None
    planned_retirement_year: dict[str, int] | None = None
    build_year: dict[str, int] | None = None


class RetrofitPotential(BaseModel):
    eligible_generators: list[str] | None = None
    uuid: str | None = None


class StorageTechnology(BaseModel):
    name: str
    region: list[int] | None = None
    id: int | None = None
    available: bool
    power_systems_type: str
    min_discharge_fraction: float | None = "0.0"
    prime_mover_type: PrimeMovers | None = "OT"
    storage_tech: StorageTech | None = None
    capital_costs_energy: ValueCurve | None = None
    capital_costs_charge: ValueCurve | None = None
    capital_costs_discharge: ValueCurve | None = None
    operation_costs: StorageCost | None = None
    unit_size_discharge: float | None = "0.0"
    unit_size_charge: float | None = "0.0"
    unit_size_energy: float | None = "0.0"
    capacity_limits_charge: MinMax | None = None
    capacity_limits_discharge: MinMax | None = None
    capacity_limits_energy: MinMax | None = None
    duration_limits: MinMax | None = None
    efficiency: InOut | None = None
    losses: float | None = "1.0"
    lifetime: int | None = "100"
    financial_data: TechnologyFinancialData | None = None


class SupplyTechnology(BaseModel):
    name: str
    power_systems_type: str
    region: list[int] | None = None
    id: int | None = None
    available: bool
    prime_mover_type: PrimeMovers | None = "OT"
    fuel: list[ThermalFuels] | None = None
    co2: dict[str, float] | None = None
    cofire_start_limits: dict[str, MinMax] | None = None
    cofire_level_limits: dict[str, MinMax] | None = None
    capital_costs: ValueCurve | None = None
    operation_costs: ThermalGenerationCost | RenewableGenerationCost | None = Field(
        None, discriminator="cost_type"
    )
    unit_size: float | None = "0.0"
    capacity_limits: MinMax | None = None
    outage_factor: float | None = "1.0"
    min_generation_fraction: float | None = "0.0"
    ramp_limits: UpDown | None = None
    time_limits: UpDown | None = None
    start_fuel_mmbtu_per_mw: float | None = "0.0"
    lifetime: int | None = "100"
    financial_data: TechnologyFinancialData | None = None


class TechnologyFinancialDataModel(BaseModel):
    name: str
    interest_rate: float | None = "0.0"
    capital_recovery_period: int
    technology_base_year: int
    id: int | None = None


class TopologyMapping(BaseModel):
    buses: list[str] | None = None
    uuid: str | None = None


class Zone(BaseModel):
    name: str
    id: int | None = None
