/**
 * Generated by orval 🍺
 * Do not edit manually.
 * PowerDynamicsOpenAPIModels
 * Power system dynamics models: DynamicGeneratorComponent and DynamicInverterComponent
 * OpenAPI spec version: 0.1.0
 */
import * as zod from "zod";

const activeRenewableControllerABPRefDefault = 1;
export const ActiveRenewableControllerAB = zod
  .object({
    bus_control: zod
      .int()
      .describe(
        "ACBus identification number for voltage control. `0` identifies the local bus connected to this component.",
      ),
    from_branch_control: zod
      .int()
      .describe(
        "Monitored branch FROM bus number for line drop compensation (if 0 generator power will be used).",
      ),
    to_branch_control: zod
      .int()
      .describe(
        "Monitored branch TO bus number for line drop compensation (if 0 generator power will be used).",
      ),
    branch_id_control: zod
      .int()
      .describe(
        "Branch circuit id for line drop compensation. If 0 generator power will be used. in psy this is a string representing the branch name",
      ),
    Freq_Flag: zod
      .boolean()
      .describe("Frequency Flag for REPCA1: `false`: disable, `true`: enable."),
    K_pg: zod.number().describe("Active power PI control proportional gain."),
    K_ig: zod.number().describe("Active power PI control integral gain."),
    T_p: zod
      .number()
      .describe("Real power measurement filter time constant. Units: s."),
    fdbd_pnts: zod
      .object({
        fdbd1: zod.number().optional(),
        fdbd2: zod.number().optional(),
      })
      .describe(
        "A pair of deadband thresholds `(fdbd1, fdbd2)` on a frequency error signal, inside which the controller does not act.",
      ),
    fe_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    P_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    T_g: zod.number().describe("Power Controller lag time constant. Units: s."),
    D_dn: zod.number().describe("Droop for over-frequency conditions."),
    D_up: zod.number().describe("Droop for under-frequency conditions."),
    dP_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    P_lim_inner: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    T_pord: zod
      .number()
      .optional()
      .describe("Power filter time constant REECB time constant. Units: s."),
    P_ref: zod
      .number()
      .default(activeRenewableControllerABPRefDefault)
      .describe("Reference Power Set-point."),
  })
  .describe(
    "Parameters of Active Power Controller including REPCA1 and REECB1.",
  );

export type ActiveRenewableControllerAB = zod.input<
  typeof ActiveRenewableControllerAB
>;
export type ActiveRenewableControllerABOutput = zod.output<
  typeof ActiveRenewableControllerAB
>;

export const RECurrentControlB = zod
  .object({
    Q_Flag: zod.boolean().describe("Q Flag used for I_qinj."),
    PQ_Flag: zod
      .boolean()
      .describe("PQ Flag used for the Current Limit Logic."),
    Vdip_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    T_rv: zod.number().describe("Voltage Filter Time Constant. Units: s."),
    dbd_pnts: zod
      .object({
        dbd1: zod.number().optional(),
        dbd2: zod.number().optional(),
      })
      .describe(
        "A pair of deadband thresholds `(dbd1, dbd2)` on a voltage or reactive-power error signal, inside which the controller does not act.",
      ),
    K_qv: zod
      .number()
      .describe(
        "Reactive current injection gain during over and undervoltage conditions.",
      ),
    Iqinj_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    V_ref0: zod
      .number()
      .describe(
        "User defined reference. If 0, `PowerSimulationsDynamics.jl` initializes to initial terminal voltage.",
      ),
    K_vp: zod
      .number()
      .describe("Voltage regulator proportional gain (used when QFlag = 1)."),
    K_vi: zod
      .number()
      .describe("Voltage regulator integral gain (used when QFlag = 1)."),
    T_iq: zod
      .number()
      .describe(
        "Time constant for low-pass filter for state q_V when QFlag = 0. Units: s.",
      ),
    I_max: zod.number().describe("Maximum limit on total converter current."),
  })
  .describe(
    "Parameters of the Inner Control part of the REECB model in PSS/E.",
  );

export type RECurrentControlB = zod.input<typeof RECurrentControlB>;
export type RECurrentControlBOutput = zod.output<typeof RECurrentControlB>;

const reactiveRenewableControllerABQRefDefault = 1;
const reactiveRenewableControllerABVRefDefault = 1;
export const ReactiveRenewableControllerAB = zod
  .object({
    bus_control: zod
      .int()
      .describe(
        "ACBus identification number for voltage control. `0` identifies the local bus connected to this component.",
      ),
    from_branch_control: zod
      .int()
      .describe(
        "Monitored branch FROM bus identification number for line drop compensation (if 0 generator power will be used).",
      ),
    to_branch_control: zod
      .int()
      .describe(
        "Monitored branch TO bus identification number for line drop compensation (if 0 generator power will be used).",
      ),
    branch_id_control: zod
      .string()
      .describe(
        "Branch circuit id for line drop compensation (as a string). If 0 generator power will be used.",
      ),
    VC_Flag: zod.boolean().describe("Voltage Compensator Flag for REPCA1."),
    Ref_Flag: zod
      .boolean()
      .describe(
        "Flag for Reactive Power Control for REPCA1. `false`: Q-control, `true`: V-control.",
      ),
    PF_Flag: zod
      .boolean()
      .describe(
        "Flag for Power Factor Control for Outer Control of REECB1. `false`: Q-control, `true`: Power Factor Control.",
      ),
    V_Flag: zod
      .boolean()
      .describe(
        "Flag for Voltage Control for Outer Control of REECB1. `false`: Voltage Control, `true`: Q-Control.",
      ),
    T_fltr: zod
      .number()
      .describe("Voltage or Q-power of REPCA Filter Time Constant. Units: s."),
    K_p: zod.number().describe("Reactive power PI control proportional gain."),
    K_i: zod.number().describe("Reactive power PI control integral gain."),
    T_ft: zod.number().describe("Reactive power lead time constant. Units: s."),
    T_fv: zod.number().describe("Reactive power lag time constant. Units: s."),
    V_frz: zod
      .number()
      .describe(
        "Voltage below which state xiq_oc (integrator state) is freeze.",
      ),
    R_c: zod
      .number()
      .describe("Line drop compensation resistance (used when VC_Flag = 1)."),
    X_c: zod
      .number()
      .describe("Line drop compensation reactance (used when VC_Flag = 1)."),
    K_c: zod
      .number()
      .describe("Reactive current compensation gain (used when VC_Flag = 0)."),
    e_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    dbd_pnts: zod
      .object({
        dbd1: zod.number().optional(),
        dbd2: zod.number().optional(),
      })
      .describe(
        "A pair of deadband thresholds `(dbd1, dbd2)` on a voltage or reactive-power error signal, inside which the controller does not act.",
      ),
    Q_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    T_p: zod
      .number()
      .describe(
        "Active power lag time constant in REECB. Used only when PF_Flag = 1. Units: s.",
      ),
    Q_lim_inner: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    V_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    K_qp: zod
      .number()
      .describe(
        "Reactive power regulator proportional gain (used when V_Flag = 1).",
      ),
    K_qi: zod
      .number()
      .describe(
        "Reactive power regulator integral gain (used when V_Flag = 1).",
      ),
    Q_ref: zod
      .number()
      .default(reactiveRenewableControllerABQRefDefault)
      .describe("Reference Reactive Power Set-point."),
    V_ref: zod
      .number()
      .default(reactiveRenewableControllerABVRefDefault)
      .describe("Reference Voltage Set-point."),
  })
  .describe(
    "Parameters of Reactive Power Controller including REPCA1 and REECB1.",
  );

export type ReactiveRenewableControllerAB = zod.input<
  typeof ReactiveRenewableControllerAB
>;
export type ReactiveRenewableControllerABOutput = zod.output<
  typeof ReactiveRenewableControllerAB
>;

const renewableEnergyConverterTypeAQRefDefault = 1;
const renewableEnergyConverterTypeARSourceDefault = 0;
const renewableEnergyConverterTypeAXSourceDefault = 100000;
export const RenewableEnergyConverterTypeA = zod
  .object({
    T_g: zod.number().describe("Converter time constant. Units: s."),
    Rrpwr: zod
      .number()
      .describe("Low Voltage Power Logic (LVPL) ramp rate limit."),
    Brkpt: zod.number().describe("LVPL characteristic voltage 2."),
    Zerox: zod.number().describe("LVPL characteristic voltage 1."),
    Lvpl1: zod.number().describe("LVPL gain."),
    Vo_lim: zod
      .number()
      .describe("Voltage limit for high voltage reactive current management."),
    Lv_pnts: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    Io_lim: zod
      .number()
      .describe(
        "Current limit for high voltage reactive current management (specified as a negative value).",
      ),
    T_fltr: zod
      .number()
      .describe(
        "Voltage filter time constant for low voltage active current management. Units: s.",
      ),
    K_hv: zod
      .number()
      .describe(
        "Overvoltage compensation gain used in the high voltage reactive current management.",
      ),
    Iqr_lims: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    Accel: zod.number().describe("Acceleration factor."),
    Lvpl_sw: zod
      .boolean()
      .describe(
        "Low voltage power logic (LVPL) switch. (`false`: LVPL not present, `true`: LVPL present).",
      ),
    Q_ref: zod
      .number()
      .default(renewableEnergyConverterTypeAQRefDefault)
      .describe("Initial condition of reactive power from power flow."),
    R_source: zod
      .number()
      .default(renewableEnergyConverterTypeARSourceDefault)
      .describe("Output resistor used for the Thevenin Equivalent."),
    X_source: zod
      .number()
      .default(renewableEnergyConverterTypeAXSourceDefault)
      .describe("Output reactance used for the Thevenin Equivalent."),
  })
  .describe(
    "Parameters of a renewable energy generator/converter model, this model corresponds to REGCA1 in PSSE.",
  );

export type RenewableEnergyConverterTypeA = zod.input<
  typeof RenewableEnergyConverterTypeA
>;
export type RenewableEnergyConverterTypeAOutput = zod.output<
  typeof RenewableEnergyConverterTypeA
>;

export const roundRotorMachineSeMin = 2;
export const roundRotorMachineSeMax = 2;

export const RoundRotorMachine = zod
  .object({
    id: zod.int().describe("Unique integer identifier for this component."),
    R: zod.number().describe("Armature resistance."),
    Td0_p: zod
      .number()
      .describe("Time constant of transient d-axis voltage. Units: s."),
    Td0_pp: zod
      .number()
      .describe("Time constant of sub-transient d-axis voltage. Units: s."),
    Tq0_p: zod
      .number()
      .describe("Time constant of transient q-axis voltage. Units: s."),
    Tq0_pp: zod
      .number()
      .describe("Time constant of sub-transient q-axis voltage. Units: s."),
    Xd: zod.number().describe("Reactance after EMF in d-axis."),
    Xq: zod.number().describe("Reactance after EMF in q-axis."),
    Xd_p: zod.number().describe("Transient reactance after EMF in d-axis."),
    Xq_p: zod.number().describe("Transient reactance after EMF in q-axis."),
    Xd_pp: zod
      .number()
      .describe(
        "Sub-Transient reactance after EMF in d-axis. Note: Xd_pp = Xq_pp.",
      ),
    Xl: zod.number().describe("Stator leakage reactance."),
    Se: zod
      .array(zod.number())
      .min(roundRotorMachineSeMin)
      .max(roundRotorMachineSeMax)
      .describe(
        "Saturation factor at 1 and 1.2 pu flux: S(1.0) = B(|psi_pp|-A)^2.",
      ),
    gamma_d1: zod.number().describe("Do not modify"),
    gamma_q1: zod.number().describe("Do not modify"),
    gamma_d2: zod.number().describe("Do not modify"),
    gamma_q2: zod.number().describe("Do not modify"),
    gamma_qd: zod.number().describe("Do not modify"),
  })
  .describe(
    "Parameters of 4-states round-rotor synchronous machine with quadratic/exponential saturation: IEEE Std 1110 5.3.2 (Model 2.2). GENROU or GENROE model in PSSE and PSLF.",
  );

export type RoundRotorMachine = zod.input<typeof RoundRotorMachine>;
export type RoundRotorMachineOutput = zod.output<typeof RoundRotorMachine>;

const sexsVRefDefault = 1;
export const Sexs = zod
  .object({
    id: zod.int().describe("Unique integer identifier for this component."),
    Ta_Tb: zod.number().describe("Ratio of lead and lag time constants."),
    Tb: zod.number().describe("Lag time constant. Units: s."),
    K: zod.number().describe("Gain."),
    Te: zod.number().describe("Field circuit time constant. Units: s."),
    V_lim: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    V_ref: zod
      .number()
      .default(sexsVRefDefault)
      .describe("Reference Voltage Set-point."),
  })
  .describe("Parameters of Simplified Excitation System Model - SEXS in PSSE.");

export type Sexs = zod.input<typeof Sexs>;
export type SexsOutput = zod.output<typeof Sexs>;

export const SteamTurbineGov1 = zod
  .object({
    id: zod.int().describe("Unique integer identifier for this component."),
    R: zod.number().describe("Droop parameter."),
    T1: zod.number().describe("Governor time constant. Units: s."),
    valve_position_limits: zod
      .object({
        max: zod.number().optional(),
        min: zod.number().optional(),
      })
      .describe(
        "A pair of values bounding a quantity from below (`min`) and from above (`max`).",
      ),
    T2: zod.number().describe("Lead Lag Lead Time constant. Units: s."),
    T3: zod.number().describe("Lead Lag Lag Time constant. Units: s."),
    D_T: zod.number().describe("Turbine Damping."),
    DB_h: zod.number().describe("Deadband for overspeed."),
    DB_l: zod.number().describe("Deadband for underspeed."),
    T_rate: zod
      .number()
      .describe("Turbine Rate. If zero, generator base is used. Units: MW."),
    P_ref: zod.number().optional().describe("Reference Power Set-point."),
  })
  .describe(
    "Steam Turbine-Governor. This model considers both TGOV1 or TGOV1DU in PSS/E.",
  );

export type SteamTurbineGov1 = zod.input<typeof SteamTurbineGov1>;
export type SteamTurbineGov1Output = zod.output<typeof SteamTurbineGov1>;
export { DbdPnts } from "../core/models";
export type { DbdPntsOutput } from "../core/models";

export { FdbdPnts } from "../core/models";
export type { FdbdPntsOutput } from "../core/models";

export { MinMax } from "../infrastructure_core/models";
export type { MinMaxOutput } from "../infrastructure_core/models";
