# generated by datamodel-codegen:
#   filename:  openapi-timeseries.json

from __future__ import annotations
from power_openapi_models.core.models import UnitSystem
from enum import Enum
from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint
from power_openapi_models.core.models import UnitSystem
from typing import Literal


class OwnerCategory(Enum):
    Component = "Component"
    SupplementalAttribute = "SupplementalAttribute"


class TimeSeriesFeatureValue(RootModel[int | float | bool | str]):
    root: int | float | bool | str = Field(
        ...,
        description="One feature value. Four kinds, matching the backing store's feature-value type: int, float, bool, str. `anyOf` rather than `oneOf` is required, not stylistic: JSON Schema's `integer` is a subset of `number`, so an integer instance matches both branches and `oneOf` — which demands exactly one match — would reject every integer feature. A float feature is compared and hashed by its bit pattern rather than by IEEE comparison, so 0.0 and -0.0 are two different series; NaN and negative zero are rejected on write because the catalog cannot store either faithfully.",
        title="TimeSeriesFeatureValue",
    )


class ElementType(RootModel[str]):
    root: str = Field(
        ...,
        description="Canonical element type of the stored array: a dtype spelling (`f64`, `f32`, `i64`, `i32`, `u64`, `u32`, `u16`, `u8`, `i16`, `i8`, `bool`) for plain scalars, else `tuple(N,dtype)` or a function-data kind (`linear_function`, `quadratic_function`, `piecewise_linear`, `piecewise_step`). It says what one timestep's value means and how it is laid out; the physical dtype of the bytes derives from it rather than being recorded separately. `linear_function` occupies 2 slots, `quadratic_function` 3; the two piecewise kinds are ragged, with the used count in the row's leading element.",
        title="ElementType",
    )


class Period(RootModel[str]):
    root: str = Field(
        ...,
        description="A time period as an ISO-8601 duration string, used for `resolution`, `horizon`, and `interval`. Two kinds, which are never equal even when their spans coincide: fixed spans (`PT1H`, `PT5M`, down to a one-millisecond floor of `PT0.001S`) and calendar spans (`P1M`, `P1Y`), whose length depends on the calendar. `PT0S` is the canonical interval of a single-window forecast. More than three fractional-second digits is rejected, so a series on a grid finer than a millisecond is not storable at all rather than storable and unreadable.",
        title="Period",
    )


class UnitSystem1(RootModel[UnitSystem]):
    root: UnitSystem


class TimeSeriesFeatures(RootModel[dict[str, TimeSeriesFeatureValue]]):
    root: dict[str, TimeSeriesFeatureValue] = Field(
        ...,
        description="User-defined key/value tags forming part of a series' identity. A map, matching the backing store's feature-map type (a BTreeMap whose sort order is load-bearing, because the hash of the feature map keys the catalog's uniqueness index). The excluded property names each already name a field of a time series or of the tuple that addresses one: consumers routinely spread a feature map into keyword arguments, where a feature called `name` or `resolution` would shadow the real field and silently change what a query means. The comparison is exact and case-sensitive — `resolution` is reserved, `Resolution` is not.",
        title="TimeSeriesFeatures",
    )


class NonSequentialTimeSeries(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["NonSequentialTimeSeries"] = Field(
        ...,
        description="Discriminator. Fixed to NonSequentialTimeSeries for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    length: conint(ge=0) = Field(
        ...,
        description="Number of timesteps. Together with `name` this is what identifies the series: its explicit, strictly-increasing timestamp vector lives in the store, content-addressed so that many irregular series sharing one time axis store it once.",
    )


class Deterministic(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Deterministic"] = Field(
        ...,
        description="Discriminator. Fixed to Deterministic for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    initial_timestamp: AwareDatetime = Field(
        ..., description="Start of the first forecast window."
    )
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. `PT0S` is the canonical interval of a single-window forecast, which has no second window to step to.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )


class DeterministicSingleTimeSeries(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["DeterministicSingleTimeSeries"] = Field(
        ...,
        description="Discriminator. Fixed to DeterministicSingleTimeSeries for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    initial_timestamp: AwareDatetime = Field(
        ..., description="Start of the first forecast window."
    )
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. `PT0S` is the canonical interval of a single-window forecast, which has no second window to step to.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )


class Probabilistic(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Probabilistic"] = Field(
        ...,
        description="Discriminator. Fixed to Probabilistic for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    initial_timestamp: AwareDatetime = Field(
        ..., description="Start of the first forecast window."
    )
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. `PT0S` is the canonical interval of a single-window forecast, which has no second window to step to.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )
    percentiles: list[float] = Field(
        ...,
        description="The percentiles this forecast carries, one per leading axis entry of the stored array.",
        min_length=1,
    )


class Scenarios(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Scenarios"] = Field(
        ...,
        description="Discriminator. Fixed to Scenarios for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    initial_timestamp: AwareDatetime = Field(
        ..., description="Start of the first forecast window."
    )
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity: two forecasts of one variable at the same resolution but different intervals — a day-ahead and a real-time forecast — are distinct series. `PT0S` is the canonical interval of a single-window forecast, which has no second window to step to.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )
    scenario_count: conint(ge=1) = Field(
        ...,
        description="Number of scenarios, one per leading axis entry of the stored array. The store's catalog has no column for this and reads it off the array's shape; it is recorded explicitly here because this layer carries no array.",
    )


class SingleTimeSeries(BaseModel):
    id: int = Field(
        ...,
        description="Surrogate primary key of the association row, the store's catalog row. Not part of the uniqueness tuple, which is (owner_id, owner_category, time_series_type, name, resolution, interval, features).",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. The producing data layer allocates both from one id stream, so an `owner_id` never collides across the two categories; `owner_category` remains required because the store's catalog contract still supports independent streams from other producers, and it is still the store's disambiguator.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["SingleTimeSeries"] = Field(
        ...,
        description="Discriminator. Fixed to SingleTimeSeries for this schema, pinned with `const` to match this repo's existing discriminators (Core/common.json's `curve_type`), which generate a plain string literal in both toolchains.",
    )
    name: str = Field(
        ...,
        description="Time series name (e.g. max_active_power). Part of the series' identity, and often carrying a disambiguating suffix; `component_field` records what the values are for.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags that are part of the series' identity: two series differing only by a feature are distinct series. Feature names that collide with a field of a series or of the tuple addressing one are rejected.",
    )
    address: str = Field(
        ...,
        description="Opaque locator for the dense data. Never parsed or interpreted here — the owner of the store decides what it means; the backing time-series store resolves it. This layer records where the values are, never the values.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The physical dtype of the stored bytes derives from this and is not recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values. Set by whoever creates the series and returned unchanged; not part of the series' identity, so two series differing only in this label are duplicates. Meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless. By convention drawn from the unit vocabulary in Core/units.json, though this field is a free-text label the store does not validate against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure (e.g. ActivePower, ReactivePower, ElectricalEnergy). Coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity kind can. It is also the only record of what the values measure when `unit_system` is a per-unit basis.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a COMPONENT_BASE series back to natural units needs the owning component's base_power. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS.",
    )
    component_field: str | None = Field(
        None,
        description="The field on the owning component or supplemental attribute whose value these values are the time-varying form of (e.g. max_active_power, rating). Free-form: it names a field in the consumer's own object model. Records what the values are for, where `name` only says which series they are.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. Element typing does not belong here — that is `element_type`.",
    )
    initial_timestamp: AwareDatetime = Field(
        ...,
        description="First timestamp of the regular grid; every later step lands at `initial_timestamp + k * resolution`. An RFC3339 string with at most 3 fractional-second digits: the store's floor is one millisecond, matching Julia's millisecond-precision DateTime.",
    )
    resolution: Period = Field(
        ...,
        description="Cadence of the regular grid. Always present for a SingleTimeSeries, and part of the series' identity.",
    )
    length: conint(ge=0) = Field(..., description="Number of timesteps.")


class TimeSeriesAssociation(
    RootModel[
        SingleTimeSeries
        | NonSequentialTimeSeries
        | Deterministic
        | DeterministicSingleTimeSeries
        | Probabilistic
        | Scenarios
    ]
):
    root: (
        SingleTimeSeries
        | NonSequentialTimeSeries
        | Deterministic
        | DeterministicSingleTimeSeries
        | Probabilistic
        | Scenarios
    ) = Field(
        ...,
        description="Metadata linking one time series to the component or supplemental attribute that owns it — the JSON form of a row in the store's `time_series_associations` catalog table. A closed set of six canonical types owned by the data layer: two static (SingleTimeSeries on a regular grid, NonSequentialTimeSeries on explicit irregular timestamps) and four forecasts. The type decides which timing fields the row carries, which is why each is its own schema rather than one row with everything nullable.\n\nDense values never appear here. `address` names the store that holds them; content hashes (data_hash, features_hash, timestamps_hash) are store-internal and deliberately absent.",
        discriminator="time_series_type",
        title="TimeSeriesAssociation",
    )
