# generated by datamodel-codegen:
#   filename:  openapi-timeseries.json

from __future__ import annotations
from power_openapi_models.core.models import UnitSystem
from pydantic import AwareDatetime, BaseModel, Field, RootModel, conint
from enum import Enum
from typing import Literal


class ArrayShapeItem(RootModel[conint(ge=0)]):
    root: conint(ge=0)


class OwnerCategory(Enum):
    Component = "Component"
    SupplementalAttribute = "SupplementalAttribute"


class TimeSeriesFeatureValue(RootModel[int | float | bool | str]):
    root: int | float | bool | str = Field(
        ...,
        description="One feature value: int, float, bool, or str. anyOf (not oneOf) because JSON Schema's integer is a subset of number. A float is compared and hashed by bit pattern, so 0.0 and -0.0 differ; NaN and negative zero are rejected on write.",
        title="TimeSeriesFeatureValue",
    )


class ElementType(RootModel[str]):
    root: str = Field(
        ...,
        description="Canonical element type of the stored array: a dtype spelling (f64, f32, i64, i32, u64, u32, u16, u8, i16, i8, bool) for scalars, else tuple(N,dtype) or a function-data kind. Says what one timestep's value means and how it is laid out.",
        title="ElementType",
    )


class TimeReference(RootModel[str]):
    root: str = Field(
        ...,
        description="How a series' timestamps are spelled: utc; zoneless for a wall clock; a fixed UTC offset (-07:00, +0530); or an IANA zone name. Not a grid: does not change what resolution steps on.",
        title="TimeReference",
    )


class Period(RootModel[str]):
    root: str = Field(
        ...,
        description="A time period as an ISO-8601 duration string, used for resolution, horizon, and interval. Fixed spans (PT1H, down to a millisecond floor) and calendar spans (P1M, P1Y) are never equal even when their spans coincide.",
        title="Period",
    )


class TimeSeriesFeatures(RootModel[dict[str, TimeSeriesFeatureValue]]):
    root: dict[str, TimeSeriesFeatureValue] = Field(
        ...,
        description="User-defined key/value tags forming part of a series' identity. Excludes names already used by a series field or by the tuple addressing one, since a feature would otherwise shadow that field. Comparison is exact and case-sensitive.",
        title="TimeSeriesFeatures",
    )


class NonSequentialTimeSeries(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["NonSequentialTimeSeries"] = Field(
        ..., description="Discriminator, fixed to NonSequentialTimeSeries for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    timestamps_uri: str | None = Field(
        None,
        description="Locator for this series' explicit timestamp vector, unique within one store. Optional; absent from the other five types, which have no explicit axis.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    length: conint(ge=0) = Field(
        ...,
        description="Number of timesteps. Together with name, identifies the series; its explicit, strictly-increasing timestamp vector lives in the store, content-addressed.",
    )


class Deterministic(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Deterministic"] = Field(
        ..., description="Discriminator, fixed to Deterministic for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    initial_timestamp: AwareDatetime = Field(..., description="Start of the first forecast window.")
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity. `PT0S` is canonical for a single-window forecast.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )


class DeterministicSingleTimeSeries(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["DeterministicSingleTimeSeries"] = Field(
        ..., description="Discriminator, fixed to DeterministicSingleTimeSeries for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    initial_timestamp: AwareDatetime = Field(..., description="Start of the first forecast window.")
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity. `PT0S` is canonical for a single-window forecast.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )


class Probabilistic(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Probabilistic"] = Field(
        ..., description="Discriminator, fixed to Probabilistic for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    initial_timestamp: AwareDatetime = Field(..., description="Start of the first forecast window.")
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity. `PT0S` is canonical for a single-window forecast.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )
    percentiles: list[float] = Field(
        ...,
        description="The percentiles this forecast carries, one per leading axis entry of the stored array.",
        min_length=1,
    )


class Scenarios(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["Scenarios"] = Field(
        ..., description="Discriminator, fixed to Scenarios for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    initial_timestamp: AwareDatetime = Field(..., description="Start of the first forecast window.")
    resolution: Period = Field(
        ...,
        description="Cadence within a forecast window. Always present for a forecast, and part of the series' identity.",
    )
    horizon: Period = Field(
        ...,
        description="Length of one forecast window. Descriptive, not part of the series' identity.",
    )
    interval: Period = Field(
        ...,
        description="Step between the start of consecutive forecast windows. Part of the series' identity. `PT0S` is canonical for a single-window forecast.",
    )
    count: conint(ge=0) = Field(
        ...,
        description="Number of forecast windows. Descriptive, not part of the series' identity.",
    )
    scenario_count: conint(ge=1) = Field(
        ...,
        description="Number of scenarios, one per leading axis entry of the stored array. Recorded explicitly here since this layer carries no array.",
    )


class SingleTimeSeries(BaseModel):
    association_id: int = Field(
        ...,
        description="Surrogate id for this association, minted by the store. Fixed once assigned and never reused; a consumer may persist it as a durable reference.",
    )
    owner_id: int = Field(
        ...,
        description="ID of the owning component or supplemental attribute. `owner_category` says which.",
    )
    owner_type: str = Field(
        ...,
        description="Type name of the owning entity. Descriptive, not part of the series' identity.",
    )
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is a component or a supplemental attribute."
    )
    time_series_type: Literal["SingleTimeSeries"] = Field(
        ..., description="Discriminator, fixed to SingleTimeSeries for this schema."
    )
    name: str = Field(
        ...,
        description="Series name (e.g. max_active_power), part of its identity. `component_field` records what the values represent.",
    )
    features: TimeSeriesFeatures = Field(
        ...,
        description="User-defined key/value tags, part of the series' identity: two series differing only by a feature are distinct. Names cannot collide with another series field.",
    )
    uri: str = Field(
        ...,
        description="Locator for the dense data, unique within its store. Format is store-defined, often a file or dataset path. Never parsed or interpreted here.",
    )
    data_hash: str | None = Field(
        None,
        description="Content hash of the stored array: SHA-256, hex-encoded. Optional — not every producer computes it.",
    )
    element_type: ElementType = Field(
        ...,
        description="What one timestep's values mean and how they are laid out. The stored dtype derives from this and is not recorded separately.",
    )
    element_shape: list[conint(ge=0)] = Field(
        ...,
        description="Per-step element shape: the trailing dims after time. An empty array means a scalar element.",
    )
    array_shape: list[ArrayShapeItem] | None = Field(
        None,
        description="Full native shape of the stored array: length, then `element_shape`. Forecasts add a horizon/percentile/scenario axis. Optional for static types.",
        min_length=1,
    )
    units: str | None = Field(
        None,
        description="Unit label for the series values, set by the writer. Drawn from the vocabulary in Core/units.json by convention, not validated against it.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Physical quantity the values measure (e.g. ActivePower, ReactivePower). Finer-grained than a dimension; the only quantity record when `unit_system` is per-unit.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration only; nothing here rescales values. Absent means unspecified, not NATURAL_UNITS.",
    )
    time_reference: TimeReference | None = Field(
        None,
        description="How this series' timestamps are spelled, returned as declared rather than relabeled as UTC. Absent means unspecified, not a UTC claim.",
    )
    component_field: str | None = Field(
        None,
        description="Field on the owning object whose time-varying values these are (e.g. max_active_power). Free-form; records what the values are for.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque payload, typically JSON, carried verbatim for the owning application to reconstruct its own objects. Never parsed here.",
    )
    initial_timestamp: AwareDatetime = Field(
        ...,
        description="First timestamp of the regular grid; each later step lands at initial_timestamp + k * resolution. An RFC3339 string with at most 3 fractional-second digits.",
    )
    resolution: Period = Field(
        ...,
        description="Cadence of the regular grid. Always present for a SingleTimeSeries, and part of the series' identity.",
    )
    length: conint(ge=0) = Field(..., description="Number of timesteps.")


class TimeSeriesAssociation(
    RootModel[
        SingleTimeSeries
        | NonSequentialTimeSeries
        | Deterministic
        | DeterministicSingleTimeSeries
        | Probabilistic
        | Scenarios
    ]
):
    root: (
        SingleTimeSeries
        | NonSequentialTimeSeries
        | Deterministic
        | DeterministicSingleTimeSeries
        | Probabilistic
        | Scenarios
    ) = Field(
        ...,
        description="Metadata linking one time series to the component or attribute that owns it. A closed set of six canonical types: two static, four forecasts. The type decides which timing fields the row carries. Dense values never appear here.",
        discriminator="time_series_type",
        title="TimeSeriesAssociation",
    )
