# generated by datamodel-codegen:
#   filename:  openapi-infrastructure-core.json

from __future__ import annotations
from enum import Enum
from pydantic import AwareDatetime, BaseModel, Field, RootModel
from typing import Any, Literal


class UnitSystem(Enum):
    COMPONENT_BASE = "COMPONENT_BASE"
    NATURAL_UNITS = "NATURAL_UNITS"


class ComplexNumber(BaseModel):
    real: float | None = None
    imag: float | None = None


class XYCoords(BaseModel):
    x: float
    y: float


class MinMax(BaseModel):
    max: float | None = Field(None, title="Max")
    min: float | None = Field(None, title="Min")


class UpDown(BaseModel):
    down: float = Field(..., title="Down")
    up: float = Field(..., title="Up")


class InOut(BaseModel):
    in_: float | None = Field(None, alias="in")
    out: float | None = None


class FromTo(BaseModel):
    from_: float | None = Field(None, alias="from", title="From")
    to: float | None = Field(None, title="To")


class FromToToFrom(BaseModel):
    from_to: float | None = Field(None, title="FromTo")
    to_from: float | None = Field(None, title="ToFrom")


class LinearFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["LINEAR"]
    proportional_term: float


class PiecewiseLinearData(BaseModel):
    function_type: Literal["PIECEWISE_LINEAR"]
    points: list[XYCoords]


class PiecewiseStepData(BaseModel):
    function_type: Literal["PIECEWISE_STEP"]
    x_coords: list[float]
    y_coords: list[float]


class QuadraticFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["QUADRATIC"]
    proportional_term: float
    quadratic_term: float


class TimeSeriesLinearFunctionData(BaseModel):
    function_type: Literal["TIME_SERIES_LINEAR"]
    association_id: int = Field(
        ...,
        description="Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.",
    )


class TimeSeriesPiecewiseLinearData(BaseModel):
    function_type: Literal["TIME_SERIES_PIECEWISE_LINEAR"]
    association_id: int = Field(
        ...,
        description="Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.",
    )


class TimeSeriesPiecewiseStepData(BaseModel):
    function_type: Literal["TIME_SERIES_PIECEWISE_STEP"]
    association_id: int = Field(
        ...,
        description="Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.",
    )


class TimeSeriesQuadraticFunctionData(BaseModel):
    function_type: Literal["TIME_SERIES_QUADRATIC"]
    association_id: int = Field(
        ...,
        description="Store-minted id of the time series association whose values supply this function data over time. Resolved against the accompanying time series store on read; minted by that store and meaningful only against it, never assigned by a document producer.",
    )


class GeographicInfo(BaseModel):
    id: int
    geo_json: dict[str, Any]


class DataSource(BaseModel):
    id: int
    organization: str | None = Field(
        None,
        description="Publishing organization, e.g. 'U.S. Energy Information Administration'.",
    )
    retrieved_at: AwareDatetime = Field(..., description="When the data was obtained.")
    dataset: str | None = Field(
        None,
        description="Dataset identifier within the publishing organization, e.g. 'EIA-860 2023, Schedule 3'.",
    )
    url: str | None = Field(None, description="URL the data was retrieved from.")
    version: str | None = Field(
        None, description="Data version or vintage, e.g. '2023 final'."
    )
    published_at: AwareDatetime | None = Field(
        None, description="When the source published the data; null if unknown."
    )
    confidence: str | None = Field(
        None, description="Confidence qualifier, e.g. 'high', 'medium'."
    )
    recorded_by: str | None = Field(
        None, description="User or agent that recorded the value."
    )
    fields: list[str] = Field(
        ...,
        description="Names of the component fields this provenance record applies to.",
    )
    extra: dict[str, str] | None = Field(
        None, description="Additional string-valued provenance metadata."
    )


class SupplementalAttributeAssociation(BaseModel):
    component_id: int = Field(
        ..., description="ID of the component the attribute describes."
    )
    component_type: str = Field(
        ...,
        description="Type name of the component the attribute describes. A denormalized label matching the relational mirror's column, used for filtering; not part of the row's identity, which is the `(component_id, attribute_id)` pair.",
    )
    attribute_id: int = Field(..., description="ID of the supplemental attribute.")
    attribute_type: str = Field(
        ...,
        description='Schema title of the referenced supplemental attribute (e.g. "EmissionsData", "GeographicInfo"). A free-form string, not an enum: new attribute types are added elsewhere in this repo continuously, and a closed enum here would go stale.',
    )


class FunctionData(
    RootModel[
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
        | TimeSeriesLinearFunctionData
        | TimeSeriesQuadraticFunctionData
        | TimeSeriesPiecewiseLinearData
        | TimeSeriesPiecewiseStepData
    ]
):
    root: (
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
        | TimeSeriesLinearFunctionData
        | TimeSeriesQuadraticFunctionData
        | TimeSeriesPiecewiseLinearData
        | TimeSeriesPiecewiseStepData
    ) = Field(
        ...,
        description="Raw mathematical data defining a function `f(x)` — coefficients or point tables with no units or interpretation attached. `function_type` selects the shape: linear, quadratic, piecewise linear through (x, y) points, or piecewise constant between x endpoints. What `x` and `y` stand for is supplied by whatever wraps this, and the `TIME_SERIES_*` variants hold a reference to a stored series in place of the numbers.",
        discriminator="function_type",
        title="FunctionData",
    )
