# generated by datamodel-codegen:
#   filename:  openapi-core.json

from __future__ import annotations
from enum import Enum
from typing import Any, Literal
from pydantic import AwareDatetime, BaseModel, Field, RootModel


class ACBusType(Enum):
    PQ = "PQ"
    PV = "PV"
    REF = "REF"
    ISOLATED = "ISOLATED"
    SLACK = "SLACK"


class StartUpStages(BaseModel):
    startup_stages_type: Literal["STAGES"] = "STAGES"
    cold: float
    hot: float
    warm: float


class LinearFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["LINEAR"]
    proportional_term: float


class QuadraticFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["QUADRATIC"]
    proportional_term: float
    quadratic_term: float


class UnitSystem(Enum):
    DEVICE_BASE = "DEVICE_BASE"
    NATURAL_UNITS = "NATURAL_UNITS"


class XYCoords(BaseModel):
    x: float
    y: float


class PiecewiseStepData(BaseModel):
    function_type: Literal["PIECEWISE_STEP"]
    x_coords: list[float]
    y_coords: list[float]


class ComplexNumber(BaseModel):
    real: float | None = None
    imag: float | None = None


class DbdPnts(BaseModel):
    dbd1: float | None = None
    dbd2: float | None = None


class Feature(RootModel[dict[str, bool | int | str]]):
    root: dict[str, bool | int | str] = Field(..., max_length=1, min_length=1)


class EnergyUnitBasis(Enum):
    MWH = "MWH"
    MWMIN = "MWMIN"


class ImpedanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_BASE = "DEVICE_BASE"


class AdmittanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_MVAR = "DEVICE_MVAR"
    DEVICE_BASE = "DEVICE_BASE"


class ShuntAdmittanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_MVAR = "DEVICE_MVAR"


class FdbdPnts(BaseModel):
    fdbd1: float | None = None
    fdbd2: float | None = None


class FromTo(BaseModel):
    from_: float | None = Field(None, alias="from", title="From")
    to: float | None = Field(None, title="To")


class FromToToFrom(BaseModel):
    from_to: float | None = Field(None, title="FromTo")
    to_from: float | None = Field(None, title="ToFrom")


class HydroReservoirCost(BaseModel):
    cost_type: Literal["HYDRO_RES"] = "HYDRO_RES"
    level_shortage_cost: float | None = 0.0
    level_surplus_cost: float | None = 0.0
    spillage_cost: float | None = 0.0


class StartUp(BaseModel):
    charge: float | None = None
    discharge: float | None = None


class InOut(BaseModel):
    in_: float | None = Field(None, alias="in")
    out: float | None = None


class MinMax(BaseModel):
    max: float | None = Field(None, title="Max")
    min: float | None = Field(None, title="Min")


class PrimeMovers(Enum):
    BA = "BA"
    BT = "BT"
    CA = "CA"
    CC = "CC"
    CE = "CE"
    CP = "CP"
    CS = "CS"
    CT = "CT"
    ES = "ES"
    FC = "FC"
    FW = "FW"
    GT = "GT"
    HA = "HA"
    HB = "HB"
    HK = "HK"
    HY = "HY"
    IC = "IC"
    PS = "PS"
    OT = "OT"
    ST = "ST"
    PVe = "PVe"
    WT = "WT"
    WS = "WS"


class ReservoirLocation(Enum):
    HEAD = "HEAD"
    TAIL = "TAIL"


class StartUpShutDown(BaseModel):
    startup: float | None = Field(None, title="StartUp")
    shutdown: float | None = Field(None, title="ShutDown")


class StorageTech(Enum):
    PTES = "PTES"
    LIB = "LIB"
    LAB = "LAB"
    FLWB = "FLWB"
    SIB = "SIB"
    ZIB = "ZIB"
    HGS = "HGS"
    LAES = "LAES"
    OTHER_CHEM = "OTHER_CHEM"
    OTHER_MECH = "OTHER_MECH"
    OTHER_THERM = "OTHER_THERM"


class TechnologyFinancialData(BaseModel):
    capital_recovery_period: int | None = None
    technology_base_year: int | None = None
    debt_fraction: float | None = None
    debt_rate: float | None = None
    return_on_equity: float | None = None
    tax_rate: float | None = None


class ThermalFuels(Enum):
    ANTHRACITE_COAL = "ANTHRACITE_COAL"
    BITUMINOUS_COAL = "BITUMINOUS_COAL"
    LIGNITE_COAL = "LIGNITE_COAL"
    SUBBITUMINOUS_COAL = "SUBBITUMINOUS_COAL"
    WASTE_COAL = "WASTE_COAL"
    REFINED_COAL = "REFINED_COAL"
    SYNTHESIS_GAS_COAL = "SYNTHESIS_GAS_COAL"
    DISTILLATE_FUEL_OIL = "DISTILLATE_FUEL_OIL"
    JET_FUEL = "JET_FUEL"
    KEROSENE = "KEROSENE"
    PETROLEUM_COKE = "PETROLEUM_COKE"
    RESIDUAL_FUEL_OIL = "RESIDUAL_FUEL_OIL"
    PROPANE = "PROPANE"
    SYNTHESIS_GAS_PETROLEUM_COKE = "SYNTHESIS_GAS_PETROLEUM_COKE"
    WASTE_OIL = "WASTE_OIL"
    BLAST_FURNACE_GAS = "BLAST_FURNACE_GAS"
    NATURAL_GAS = "NATURAL_GAS"
    OTHER_GAS = "OTHER_GAS"
    AG_BYPRODUCT = "AG_BYPRODUCT"
    MUNICIPAL_WASTE = "MUNICIPAL_WASTE"
    OTHER_BIOMASS_SOLIDS = "OTHER_BIOMASS_SOLIDS"
    WOOD_WASTE_SOLIDS = "WOOD_WASTE_SOLIDS"
    OTHER_BIOMASS_LIQUIDS = "OTHER_BIOMASS_LIQUIDS"
    SLUDGE_WASTE = "SLUDGE_WASTE"
    BLACK_LIQUOR = "BLACK_LIQUOR"
    WOOD_WASTE_LIQUIDS = "WOOD_WASTE_LIQUIDS"
    LANDFILL_GAS = "LANDFILL_GAS"
    OTHER_BIOMASS_GAS = "OTHER_BIOMASS_GAS"
    NUCLEAR = "NUCLEAR"
    WASTE_HEAT = "WASTE_HEAT"
    TIRE_DERIVED_FUEL = "TIRE_DERIVED_FUEL"
    COAL = "COAL"
    GEOTHERMAL = "GEOTHERMAL"
    OTHER = "OTHER"


class TurbinePump(BaseModel):
    turbine: float
    pump: float


class UpDown(BaseModel):
    down: float = Field(..., title="Down")
    up: float = Field(..., title="Up")


class GeographicInfo(BaseModel):
    id: int
    geo_json: dict[str, Any]


class DataSource(BaseModel):
    id: int
    organization: str | None = Field(
        None,
        description="Publishing organization, e.g. 'U.S. Energy Information Administration'.",
    )
    retrieved_at: AwareDatetime = Field(..., description="When the data was obtained.")
    dataset: str | None = Field(
        None,
        description="Dataset identifier within the publishing organization, e.g. 'EIA-860 2023, Schedule 3'.",
    )
    url: str | None = Field(None, description="URL the data was retrieved from.")
    version: str | None = Field(
        None, description="Data version or vintage, e.g. '2023 final'."
    )
    published_at: AwareDatetime | None = Field(
        None, description="When the source published the data; null if unknown."
    )
    confidence: str | None = Field(
        None, description="Confidence qualifier, e.g. 'high', 'medium'."
    )
    recorded_by: str | None = Field(
        None, description="User or agent that recorded the value."
    )
    fields: list[str] = Field(
        ...,
        description="Names of the component fields this provenance record applies to.",
    )
    extra: dict[str, str] | None = Field(
        None, description="Additional string-valued provenance metadata."
    )


class SupplementalAttributeAssociation(BaseModel):
    attribute_id: int = Field(..., description="ID of the supplemental attribute.")
    entity_id: int = Field(
        ..., description="ID of the component the attribute describes."
    )
    attribute_type: str = Field(
        ...,
        description='Schema title of the referenced supplemental attribute (e.g. "EmissionsData", "GeographicInfo"). A free-form string, not an enum: new attribute types are added elsewhere in this repo continuously, and a closed enum here would go stale.',
    )


class OwnerCategory(Enum):
    Component = "Component"
    SupplementalAttribute = "SupplementalAttribute"


class TimeSeriesAssociation(BaseModel):
    id: int
    time_series_type: str
    initial_timestamp: AwareDatetime
    resolution: str = Field(..., description="ISO 8601 duration (e.g., PT1H, PT5M).")
    horizon: str | None = Field(
        None, description="ISO 8601 duration for forecast horizon."
    )
    interval: str | None = Field(
        None, description="ISO 8601 duration for forecast interval."
    )
    window_count: int | None = None
    length: int | None = None
    name: str = Field(..., description="Time series name (e.g., max_active_power).")
    owner_id: int = Field(..., description="ID of the owning component.")
    owner_type: str = Field(..., description="Type name of the owning component.")
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is component or supplemental attribute"
    )
    features: list[Feature]
    element_type: str | None = Field(
        None,
        description="Canonical element type of the stored array: a dtype spelling (`f64`, `f32`, `i64`, `i32`, `u64`, `bool`) for plain scalars, else `tuple(N,dtype)` or a function-data kind (`linear_function`, `quadratic_function`, `piecewise_linear`, `piecewise_step`). It says what one timestep's value *means* and how it is laid out; the physical dtype of the bytes is derived from it rather than recorded separately. Unlike `units` and `quantity_kind` this is not a user-facing label — the writing package derives it from the array.",
    )
    units: str | None = Field(
        None,
        description="Unit string for the series values; must be a unit from the Core/units.json vocabulary allowed for `quantity_kind`. Absent when the series declares no unit, and meaningless on its own when `unit_system` is a per-unit basis, where the values are dimensionless.",
    )
    quantity_kind: str | None = Field(
        None,
        description="Kind of physical quantity the values measure; must be a `quantity_types` name from the Core/units.json vocabulary (e.g. ActivePower, ReactivePower, ElectricalEnergy). Not an enum here because Core/units.json is the single source of truth for the vocabulary and duplicating it would give it two homes. It is coarser than `units` but finer than a dimension: ActivePower, ReactivePower, and ApparentPower share the dimension {M:1,L:2,T:-3}, so a dimension cannot tell them apart and a quantity type can. It is also the only record of what the values measure when `unit_system` is a per-unit basis and they are therefore dimensionless.",
    )
    unit_system: UnitSystem | None = Field(
        None,
        description="Basis the series values are already expressed in. A declaration, not a conversion: nothing here rescales values, and converting a DEVICE_BASE series back to natural units needs the owning component's base_power — as with every other per-unit quantity, system-base data records its base there and rides as DEVICE_BASE. Absent means unspecified, which is deliberately not the same as NATURAL_UNITS: a series that never declared a basis must not be read as though someone had said its values were natural.",
    )
    application_data: str | None = Field(
        None,
        description="Opaque, package-owned payload (typically JSON) carried verbatim for an application to reconstruct its own domain objects. Never parsed or interpreted here, and end users are not expected to set it. This is a property of the association, not the component-level `ext` that the PSY parity allowlist drops as an infra field. Element typing does *not* belong here — that is `element_type`, which this layer owns and validates.",
    )


class PollutantType(Enum):
    CO2 = "CO2"
    CO2E = "CO2E"
    CH4 = "CH4"
    N2O = "N2O"
    NOX = "NOX"
    SO2 = "SO2"
    CO = "CO"
    VOC = "VOC"
    PM25 = "PM25"
    PM10 = "PM10"
    HG = "HG"
    HAP = "HAP"
    CUSTOM = "CUSTOM"


class EmissionBasis(Enum):
    FUEL_INPUT = "FUEL_INPUT"
    POWER_OUTPUT = "POWER_OUTPUT"


class MassUnit(Enum):
    KG = "KG"
    LB = "LB"
    SHORT_TON = "SHORT_TON"
    METRIC_TON = "METRIC_TON"


class EnergyUnit(Enum):
    MMBTU = "MMBTU"
    GJ = "GJ"
    MWH = "MWH"


class PiecewiseLinearData(BaseModel):
    function_type: Literal["PIECEWISE_LINEAR"]
    points: list[XYCoords]


class AverageRateCurve(BaseModel):
    curve_type: Literal["AVERAGE_RATE"]
    function_data: LinearFunctionData | PiecewiseStepData = Field(
        ..., discriminator="function_type"
    )
    initial_input: float | None = None
    input_at_zero: float | None = None


class IncrementalCurve(BaseModel):
    curve_type: Literal["INCREMENTAL"]
    function_data: LinearFunctionData | PiecewiseStepData = Field(
        ..., discriminator="function_type"
    )
    initial_input: float | None = None
    input_at_zero: float | None = None


class FunctionData(
    RootModel[
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
    ]
):
    root: (
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
    ) = Field(..., discriminator="function_type", title="FunctionData")


class InputOutputCurve(BaseModel):
    curve_type: Literal["INPUT_OUTPUT"]
    function_data: QuadraticFunctionData | LinearFunctionData | PiecewiseLinearData = (
        Field(..., discriminator="function_type")
    )
    input_at_zero: float | None = None


class ValueCurve(RootModel[InputOutputCurve | IncrementalCurve | AverageRateCurve]):
    root: InputOutputCurve | IncrementalCurve | AverageRateCurve = Field(
        ..., discriminator="curve_type", title="ValueCurve"
    )


class FuelCurve(BaseModel):
    fuel_cost: str | float
    power_units: UnitSystem
    startup_fuel_offtake: InputOutputCurve | None = Field(
        None,
        description="Fuel consumed during startup, as a curve in the unit's fuel units.",
    )
    value_curve: ValueCurve
    variable_cost_type: Literal["FUEL"]
    vom_cost: InputOutputCurve


class TwoTerminalLoss(RootModel[InputOutputCurve | IncrementalCurve]):
    root: InputOutputCurve | IncrementalCurve = Field(
        {
            "curve_type": "INPUT_OUTPUT",
            "function_data": {
                "function_type": "LINEAR",
                "constant_term": 0,
                "proportional_term": 0,
            },
        },
        discriminator="curve_type",
        title="TwoTerminalLoss",
        validate_default=True,
    )


class CostCurve(BaseModel):
    power_units: UnitSystem = UnitSystem.NATURAL_UNITS
    value_curve: ValueCurve
    variable_cost_type: Literal["COST"]
    vom_cost: InputOutputCurve


class RenewableGenerationCost(BaseModel):
    cost_type: Literal["RENEWABLE"] = "RENEWABLE"
    curtailment_cost: CostCurve | None = Field(
        {
            "variable_cost_type": "COST",
            "value_curve": {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
            },
            "vom_cost": {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
            },
        },
        validate_default=True,
    )
    variable: CostCurve
    fixed: float | None = 0.0


class ProductionVariableCostCurve(RootModel[CostCurve | FuelCurve]):
    root: CostCurve | FuelCurve = Field(
        ..., discriminator="variable_cost_type", title="ProductionVariableCostCurve"
    )


class StorageCost(BaseModel):
    cost_type: Literal["STORAGE"] = "STORAGE"
    charge_variable_cost: CostCurve | None = None
    discharge_variable_cost: CostCurve | None = None
    fixed: float
    shut_down: float
    start_up: float | StartUp
    energy_shortage_cost: float | None = 0.0
    energy_surplus_cost: float | None = 0.0


class ImportExportCost(BaseModel):
    cost_type: Literal["IMPORTEXPORT"] = "IMPORTEXPORT"
    import_offer_curves: CostCurve | None = None
    export_offer_curves: CostCurve | None = None
    energy_import_weekly_limit: float
    energy_export_weekly_limit: float


class LoadCost(BaseModel):
    cost_type: Literal["LOAD"] = "LOAD"
    fixed: float | None = 0.0
    variable: CostCurve


class MarketBidCost(BaseModel):
    cost_type: Literal["MARKET_BID"] = "MARKET_BID"
    no_load_cost: InputOutputCurve = Field(
        ...,
        description="No load cost. Legacy scalar promotion: a bare scalar value `s` from a legacy source converts to an `InputOutputCurve` of `LinearFunctionData` with `constant_term = s` and `proportional_term = 0`.",
    )
    start_up: StartUpStages = Field(
        ...,
        description="Start-up cost at different stages of the thermal cycle (hot, warm, cold).",
    )
    shut_down: InputOutputCurve = Field(
        ...,
        description="Shut-down cost. Legacy scalar promotion: a bare scalar value `s` from a legacy source converts to an `InputOutputCurve` of `LinearFunctionData` with `constant_term = s` and `proportional_term = 0`.",
    )
    incremental_offer_curves: CostCurve = Field(
        ...,
        description="Sell offer curves data as a `CostCurve` of `PiecewiseIncrementalCurve`.",
    )
    decremental_offer_curves: CostCurve = Field(
        ...,
        description="Buy offer curves data as a `CostCurve` of `PiecewiseIncrementalCurve`.",
    )
    ancillary_service_offers: list[int] = Field(
        ...,
        description="IDs of the ancillary service components that this market bid offers into.",
    )


class HydroGenerationCost(BaseModel):
    cost_type: Literal["HYDRO_GEN"] = "HYDRO_GEN"
    fixed: float | None = 0.0
    variable: ProductionVariableCostCurve


class ThermalGenerationCost(BaseModel):
    cost_type: Literal["THERMAL"] = "THERMAL"
    fixed: float = Field(
        ...,
        description="Fixed cost of keeping the unit online. For some cost represenations this field can be duplicative",
    )
    shut_down: float = Field(..., description="Cost to turn the unit off")
    start_up: float | StartUpStages = Field(
        ..., description="Start-up cost can take linear or multi-stage cost"
    )
    variable: ProductionVariableCostCurve


class HydroStorageGenerationCost(RootModel[HydroGenerationCost | StorageCost]):
    root: HydroGenerationCost | StorageCost = Field(
        ..., discriminator="cost_type", title="HydroStorageGenerationCost"
    )


class GenericOperationCost(
    RootModel[ThermalGenerationCost | RenewableGenerationCost | HydroGenerationCost]
):
    root: ThermalGenerationCost | RenewableGenerationCost | HydroGenerationCost = Field(
        ..., discriminator="cost_type", title="GenericOperationCost"
    )
