# generated by datamodel-codegen:
#   filename:  openapi-core.json

from __future__ import annotations
from enum import Enum
from typing import Any, Literal
from pydantic import AwareDatetime, BaseModel, Field, RootModel
from uuid import UUID


class ACBusType(Enum):
    PQ = "PQ"
    PV = "PV"
    REF = "REF"
    ISOLATED = "ISOLATED"
    SLACK = "SLACK"


class StartUpStages(BaseModel):
    startup_stages_type: Literal["STAGES"] = "STAGES"
    cold: float
    hot: float
    warm: float


class LinearFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["LINEAR"]
    proportional_term: float


class QuadraticFunctionData(BaseModel):
    constant_term: float
    function_type: Literal["QUADRATIC"]
    proportional_term: float
    quadratic_term: float


class UnitSystem(Enum):
    DEVICE_BASE = "DEVICE_BASE"
    NATURAL_UNITS = "NATURAL_UNITS"


class XYCoords(BaseModel):
    x: float
    y: float


class PiecewiseStepData(BaseModel):
    function_type: Literal["PIECEWISE_STEP"]
    x_coords: list[float]
    y_coords: list[float]


class ComplexNumber(BaseModel):
    real: float | None = None
    imag: float | None = None


class DbdPnts(BaseModel):
    dbd1: float | None = None
    dbd2: float | None = None


class Feature(RootModel[dict[str, bool | int | str]]):
    root: dict[str, bool | int | str]


class EnergyUnitBasis(Enum):
    MWH = "MWH"
    MWMIN = "MWMIN"


class ImpedanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_BASE = "DEVICE_BASE"


class AdmittanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_MVAR = "DEVICE_MVAR"
    DEVICE_BASE = "DEVICE_BASE"


class ShuntAdmittanceUnitBasis(Enum):
    NATURAL_UNITS = "NATURAL_UNITS"
    DEVICE_MVAR = "DEVICE_MVAR"


class FdbdPnts(BaseModel):
    fdbd1: float | None = None
    fdbd2: float | None = None


class FromTo(BaseModel):
    from_: float | None = Field(None, alias="from", title="From")
    to: float | None = Field(None, title="To")


class FromToToFrom(BaseModel):
    from_to: float | None = Field(None, title="FromTo")
    to_from: float | None = Field(None, title="ToFrom")


class HydroReservoirCost(BaseModel):
    cost_type: Literal["HYDRO_RES"] = "HYDRO_RES"
    level_shortage_cost: float | None = 0.0
    level_surplus_cost: float | None = 0.0
    spillage_cost: float | None = 0.0


class StartUp(BaseModel):
    charge: float | None = None
    discharge: float | None = None


class InOut(BaseModel):
    in_: float | None = Field(None, alias="in")
    out: float | None = None


class MinMax(BaseModel):
    max: float | None = Field(None, title="Max")
    min: float | None = Field(None, title="Min")


class PrimeMovers(Enum):
    BA = "BA"
    BT = "BT"
    CA = "CA"
    CC = "CC"
    CE = "CE"
    CP = "CP"
    CS = "CS"
    CT = "CT"
    ES = "ES"
    FC = "FC"
    FW = "FW"
    GT = "GT"
    HA = "HA"
    HB = "HB"
    HK = "HK"
    HY = "HY"
    IC = "IC"
    PS = "PS"
    OT = "OT"
    ST = "ST"
    PVe = "PVe"
    WT = "WT"
    WS = "WS"


class ReservoirLocation(Enum):
    HEAD = "HEAD"
    TAIL = "TAIL"


class StartUpShutDown(BaseModel):
    startup: float | None = Field(None, title="StartUp")
    shutdown: float | None = Field(None, title="ShutDown")


class StorageTech(Enum):
    PTES = "PTES"
    LIB = "LIB"
    LAB = "LAB"
    FLWB = "FLWB"
    SIB = "SIB"
    ZIB = "ZIB"
    HGS = "HGS"
    LAES = "LAES"
    OTHER_CHEM = "OTHER_CHEM"
    OTHER_MECH = "OTHER_MECH"
    OTHER_THERM = "OTHER_THERM"


class TechnologyFinancialData(BaseModel):
    capital_recovery_period: int | None = None
    technology_base_year: int | None = None
    debt_fraction: float | None = None
    debt_rate: float | None = None
    return_on_equity: float | None = None
    tax_rate: float | None = None


class ThermalFuels(Enum):
    ANTHRACITE_COAL = "ANTHRACITE_COAL"
    BITUMINOUS_COAL = "BITUMINOUS_COAL"
    LIGNITE_COAL = "LIGNITE_COAL"
    SUBBITUMINOUS_COAL = "SUBBITUMINOUS_COAL"
    WASTE_COAL = "WASTE_COAL"
    REFINED_COAL = "REFINED_COAL"
    SYNTHESIS_GAS_COAL = "SYNTHESIS_GAS_COAL"
    DISTILLATE_FUEL_OIL = "DISTILLATE_FUEL_OIL"
    JET_FUEL = "JET_FUEL"
    KEROSENE = "KEROSENE"
    PETROLEUM_COKE = "PETROLEUM_COKE"
    RESIDUAL_FUEL_OIL = "RESIDUAL_FUEL_OIL"
    PROPANE = "PROPANE"
    SYNTHESIS_GAS_PETROLEUM_COKE = "SYNTHESIS_GAS_PETROLEUM_COKE"
    WASTE_OIL = "WASTE_OIL"
    BLASTE_FURNACE_GAS = "BLASTE_FURNACE_GAS"
    NATURAL_GAS = "NATURAL_GAS"
    OTHER_GAS = "OTHER_GAS"
    AG_BYPRODUCT = "AG_BYPRODUCT"
    MUNICIPAL_WASTE = "MUNICIPAL_WASTE"
    OTHER_BIOMASS_SOLIDS = "OTHER_BIOMASS_SOLIDS"
    WOOD_WASTE_SOLIDS = "WOOD_WASTE_SOLIDS"
    OTHER_BIOMASS_LIQUIDS = "OTHER_BIOMASS_LIQUIDS"
    SLUDGE_WASTE = "SLUDGE_WASTE"
    BLACK_LIQUOR = "BLACK_LIQUOR"
    WOOD_WASTE_LIQUIDS = "WOOD_WASTE_LIQUIDS"
    LANDFILL_GAS = "LANDFILL_GAS"
    OTHEHR_BIOMASS_GAS = "OTHEHR_BIOMASS_GAS"
    NUCLEAR = "NUCLEAR"
    WASTE_HEAT = "WASTE_HEAT"
    TIREDERIVED_FUEL = "TIREDERIVED_FUEL"
    COAL = "COAL"
    GEOTHERMAL = "GEOTHERMAL"
    OTHER = "OTHER"


class TurbinePump(BaseModel):
    turbine: float
    pump: float


class UpDown(BaseModel):
    down: float = Field(..., title="Down")
    up: float = Field(..., title="Up")


class GeographicInfo(BaseModel):
    id: int
    geo_json: dict[str, Any]


class Role(Enum):
    CT = "CT"
    CA = "CA"


class SupplementalAttributeAssociation(BaseModel):
    attribute_id: int = Field(
        ...,
        description="ID of the supplemental attribute, or of the service, for a membership row.",
    )
    entity_id: int = Field(
        ...,
        description="ID of the component, or other entity, that the attribute describes or the service contains.",
    )
    attribute_type: str = Field(
        ...,
        description='Schema title of the referenced supplemental attribute or service (e.g. "EmissionsData", "GeographicInfo", "ThermalPowerPlant", "CombinedCycleBlock", "OnlineReserve"). A free-form string, not an enum: new attribute and service types are added elsewhere in this repo continuously, and a closed enum here would go stale.',
    )
    group_index: int | None = Field(
        None,
        description="Optional group number within the parent named by attribute_id: the shaft/penstock/PCC number for a ThermalPowerPlant, HydroPowerPlant, or RenewablePowerPlant row, the HRSG index for a CombinedCycleBlock row, or the exclusion group number for an exclusion grouping. Omitted for a plain supplemental attribute or a service membership, neither of which has a group to index.",
    )
    role: Role | None = Field(
        None,
        description="Optional role of entity_id within the parent named by attribute_id. Meaningful only for a CombinedCycleBlock row, where it is CT (combustion turbine) or CA (combustion-augmented steam); omitted for every other attribute_type.",
    )


class OwnerCategory(Enum):
    Component = "Component"
    SupplementalAttribute = "SupplementalAttribute"


class TimeSeriesAssociation(BaseModel):
    id: int
    time_series_uuid: UUID = Field(
        ...,
        description="UUID of the time series data. May reference inline data or an external store (e.g., HDF5).",
    )
    time_series_type: str
    initial_timestamp: AwareDatetime
    resolution: str = Field(..., description="ISO 8601 duration (e.g., PT1H, PT5M).")
    horizon: str | None = Field(
        None, description="ISO 8601 duration for forecast horizon."
    )
    interval: str | None = Field(
        None, description="ISO 8601 duration for forecast interval."
    )
    window_count: int | None = None
    length: int | None = None
    name: str = Field(..., description="Time series name (e.g., max_active_power).")
    owner_id: int = Field(..., description="ID of the owning component.")
    owner_type: str = Field(..., description="Type name of the owning component.")
    owner_category: OwnerCategory = Field(
        ..., description="Whether the owner is component or supplemental attribute"
    )
    features: list[Feature]
    scaling_factor_multiplier: str | None = Field(
        None,
        description="Dot-encoded function name like PowerSystems.get_max_active_power.",
    )
    metadata_uuid: UUID = Field(
        ..., description="Usually unique for each association, but not necessarily"
    )
    units: str | None = Field(
        None,
        description="Unit string for the series values; must be a unit from the Core/units.json vocabulary for the series' quantity type.",
    )


class PollutantType(Enum):
    CO2 = "CO2"
    CO2E = "CO2E"
    CH4 = "CH4"
    N2O = "N2O"
    NOX = "NOX"
    SO2 = "SO2"
    CO = "CO"
    VOC = "VOC"
    PM25 = "PM25"
    PM10 = "PM10"
    HG = "HG"
    HAP = "HAP"
    CUSTOM = "CUSTOM"


class EmissionBasis(Enum):
    FUEL_INPUT = "FUEL_INPUT"
    POWER_OUTPUT = "POWER_OUTPUT"


class MassUnit(Enum):
    KG = "KG"
    LB = "LB"
    SHORT_TON = "SHORT_TON"
    METRIC_TON = "METRIC_TON"


class EnergyUnit(Enum):
    MMBTU = "MMBTU"
    GJ = "GJ"
    MWH = "MWH"


class PiecewiseLinearData(BaseModel):
    function_type: Literal["PIECEWISE_LINEAR"]
    points: list[XYCoords]


class AverageRateCurve(BaseModel):
    curve_type: Literal["AVERAGE_RATE"]
    function_data: LinearFunctionData | PiecewiseStepData = Field(
        ..., discriminator="function_type"
    )
    initial_input: float | None = None
    input_at_zero: float | None = None


class IncrementalCurve(BaseModel):
    curve_type: Literal["INCREMENTAL"]
    function_data: LinearFunctionData | PiecewiseStepData = Field(
        ..., discriminator="function_type"
    )
    initial_input: float | None = None
    input_at_zero: float | None = None


class FunctionData(
    RootModel[
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
    ]
):
    root: (
        LinearFunctionData
        | QuadraticFunctionData
        | PiecewiseLinearData
        | PiecewiseStepData
    ) = Field(..., discriminator="function_type", title="FunctionData")


class InputOutputCurve(BaseModel):
    curve_type: Literal["INPUT_OUTPUT"]
    function_data: QuadraticFunctionData | LinearFunctionData | PiecewiseLinearData = (
        Field(..., discriminator="function_type")
    )
    input_at_zero: float | None = None


class ValueCurve(RootModel[InputOutputCurve | IncrementalCurve | AverageRateCurve]):
    root: InputOutputCurve | IncrementalCurve | AverageRateCurve = Field(
        ..., discriminator="curve_type", title="ValueCurve"
    )


class FuelCurve(BaseModel):
    fuel_cost: str | float
    power_units: UnitSystem
    startup_fuel_offtake: InputOutputCurve | None = Field(
        None,
        description="Fuel consumed during startup, as a curve in the unit's fuel units.",
    )
    value_curve: ValueCurve
    variable_cost_type: Literal["FUEL"]
    vom_cost: InputOutputCurve


class TwoTerminalLoss(RootModel[InputOutputCurve | IncrementalCurve]):
    root: InputOutputCurve | IncrementalCurve = Field(
        default_factory=lambda: InputOutputCurve.model_validate(
            {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
                "input_at_zero": 0,
            }
        ),
        discriminator="curve_type",
        title="TwoTerminalLoss",
    )


class CostCurve(BaseModel):
    power_units: UnitSystem = UnitSystem.NATURAL_UNITS
    value_curve: ValueCurve
    variable_cost_type: Literal["COST"]
    vom_cost: InputOutputCurve = Field(
        default_factory=lambda: InputOutputCurve.model_validate(
            {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
                "input_at_zero": 0,
            }
        )
    )


class RenewableGenerationCost(BaseModel):
    cost_type: Literal["RENEWABLE"] = "RENEWABLE"
    curtailment_cost: CostCurve | None = Field(
        default_factory=lambda: CostCurve.model_validate(
            {
                "variable_cost_type": "COST",
                "value_curve": {
                    "curve_type": "INPUT_OUTPUT",
                    "function_data": {
                        "function_type": "LINEAR",
                        "constant_term": 0,
                        "proportional_term": 0,
                    },
                    "input_at_zero": 0,
                },
                "vom_cost": {
                    "curve_type": "INPUT_OUTPUT",
                    "function_data": {
                        "function_type": "LINEAR",
                        "constant_term": 0,
                        "proportional_term": 0,
                    },
                    "input_at_zero": 0,
                },
            }
        )
    )
    variable: CostCurve
    fixed: float | None = 0.0


class ProductionVariableCostCurve(RootModel[CostCurve | FuelCurve]):
    root: CostCurve | FuelCurve = Field(
        ..., discriminator="variable_cost_type", title="ProductionVariableCostCurve"
    )


class StorageCost(BaseModel):
    cost_type: Literal["STORAGE"] = "STORAGE"
    charge_variable_cost: CostCurve | None = None
    discharge_variable_cost: CostCurve | None = None
    fixed: float
    shut_down: float
    start_up: float | StartUp
    energy_shortage_cost: float | None = 0.0
    energy_surplus_cost: float | None = 0.0


class ImportExportCost(BaseModel):
    cost_type: Literal["IMPORTEXPORT"] = "IMPORTEXPORT"
    import_offer_curves: CostCurve | None = None
    export_offer_curves: CostCurve | None = None
    energy_import_weekly_limit: float
    energy_export_weekly_limit: float


class LoadCost(BaseModel):
    cost_type: Literal["LOAD"] = "LOAD"
    fixed: float | None = 0.0
    variable: CostCurve


class MarketBidCost(BaseModel):
    cost_type: Literal["MARKET_BID"] = "MARKET_BID"
    no_load_cost: InputOutputCurve = Field(
        default_factory=lambda: InputOutputCurve.model_validate(
            {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
                "input_at_zero": 0,
            }
        ),
        description="No load cost. Legacy scalar promotion: a bare scalar value `s` from a legacy source converts to an `InputOutputCurve` of `LinearFunctionData` with `constant_term = s` and `proportional_term = 0`.",
    )
    start_up: StartUpStages = Field(
        ...,
        description="Start-up cost at different stages of the thermal cycle (hot, warm, cold).",
    )
    shut_down: InputOutputCurve = Field(
        default_factory=lambda: InputOutputCurve.model_validate(
            {
                "curve_type": "INPUT_OUTPUT",
                "function_data": {
                    "function_type": "LINEAR",
                    "constant_term": 0,
                    "proportional_term": 0,
                },
                "input_at_zero": 0,
            }
        ),
        description="Shut-down cost. Legacy scalar promotion: a bare scalar value `s` from a legacy source converts to an `InputOutputCurve` of `LinearFunctionData` with `constant_term = s` and `proportional_term = 0`.",
    )
    incremental_offer_curves: CostCurve = Field(
        ...,
        description="Sell offer curves data as a `CostCurve` of `PiecewiseIncrementalCurve`.",
    )
    decremental_offer_curves: CostCurve = Field(
        ...,
        description="Buy offer curves data as a `CostCurve` of `PiecewiseIncrementalCurve`.",
    )
    ancillary_service_offers: list[int] = Field(
        ...,
        description="IDs of the ancillary service components that this market bid offers into.",
    )


class HydroGenerationCost(BaseModel):
    cost_type: Literal["HYDRO_GEN"] = "HYDRO_GEN"
    fixed: float | None = 0.0
    variable: ProductionVariableCostCurve


class ThermalGenerationCost(BaseModel):
    cost_type: Literal["THERMAL"] = "THERMAL"
    fixed: float = Field(
        ...,
        description="Fixed cost of keeping the unit online. For some cost represenations this field can be duplicative",
    )
    shut_down: float = Field(..., description="Cost to turn the unit off")
    start_up: float | StartUpStages = Field(
        ...,
        description="Start-up cost can take linear or multi-stage cost",
    )
    variable: ProductionVariableCostCurve


class HydroStorageGenerationCost(RootModel[HydroGenerationCost | StorageCost]):
    root: HydroGenerationCost | StorageCost = Field(
        ..., discriminator="cost_type", title="HydroStorageGenerationCost"
    )


class GenericOperationCost(
    RootModel[ThermalGenerationCost | RenewableGenerationCost | HydroGenerationCost]
):
    root: ThermalGenerationCost | RenewableGenerationCost | HydroGenerationCost = Field(
        ..., discriminator="cost_type", title="GenericOperationCost"
    )
